#!/usr/bin/env python3
"""Fake gh: records its argv, cwd and the SHA-256 of every file argument in $FAKE_GH_LOG."""
import hashlib
import json
import os
import sys

args = sys.argv[1:]
files = {a: hashlib.sha256(open(a, 'rb').read()).hexdigest() for a in args if os.path.isfile(a)}
with open(os.environ['FAKE_GH_LOG'], 'a') as log:
    log.write(json.dumps(dict(args=args, cwd=os.getcwd(), files=files)) + '\n')
sys.exit(int(os.environ.get('FAKE_GH_EXIT', '0')))
