#!/bin/sh
# Fake uname: the host platform comes from FAKE_UNAME ("<kernel> <machine>").
# shellcheck disable=SC2086  # split "<kernel> <machine>" on purpose
set -- "$1" ${FAKE_UNAME:-Darwin arm64}
case "$1" in
  -s) echo "$2" ;;
  -m) echo "$3" ;;
  *) exit 1 ;;
esac
