//! Migration runner over the codegen'd `migrations` manifest.
//!
//! Applies up files in version order, down files in reverse. The manifest
//! itself is generated by src-zig/tools/gen_migrations.zig from the SQL
//! files under the repo-root `migrations/` directory.
const std = @import("std");
const sqlite = @import("sqlite.zig");
const migrations = @import("migrations");

/// The highest schema version this binary's embedded migrations can bring
/// the database to. Used by `assertSchemaCompatible` to detect a DB that
/// was migrated by a newer binary.
pub const embedded_max: u32 = if (migrations.all.len > 0)
    migrations.all[migrations.all.len - 1].version
else
    0;

pub const Error = error{
    /// The database's `schema_migrations` max version exceeds the highest
    /// migration this binary knows about. The binary must be upgraded.
    SchemaVersionAhead,
    SchemaVersionGap,
    InvalidMigrationSet,
};

/// Apply every up migration that hasn't run yet, in version order. Each
/// migration runs in its own explicit transaction. `sqlite3_exec` does not
/// make a multi-statement script atomic by itself.
///
/// Idempotent: reads `max(version)` from `schema_migrations` to decide
/// where to resume. The table is absent on a fresh DB — the query fails,
/// we treat that as "nothing applied yet" and run from version 1.
pub fn applyAll(db: *sqlite.Db, alloc: std.mem.Allocator) !void {
    try validateEmbeddedMigrations();
    const max_applied: u32 = if (db.intQuery(
        "select coalesce(max(version), 0) from schema_migrations",
    )) |v| @intCast(v) else |_| 0;

    for (migrations.all) |m| {
        if (m.version <= max_applied) continue;
        try applyOne(db, alloc, m.up);
    }
}

fn validateEmbeddedMigrations() Error!void {
    for (migrations.all, 0..) |m, i| {
        const expected: u32 = @intCast(i + 1);
        if (m.version != expected) return Error.InvalidMigrationSet;
    }
}

fn applyOne(db: *sqlite.Db, alloc: std.mem.Allocator, sql: []const u8) !void {
    try db.exec("begin immediate");
    var committed = false;
    defer if (!committed) db.exec("rollback") catch {};
    try db.execSlice(alloc, sql);
    try db.exec("commit");
    committed = true;
}

/// Assert that the database's schema version does not exceed what this
/// binary knows. Fires only when `db_version > embedded_max`.
///
/// Call this AFTER `applyAll` so that a stale DB (db_version <
/// embedded_max) has already been brought up to date before the check
/// runs.  A fresh DB (no `schema_migrations` table) maps to db_version=0
/// and never trips the guard.
///
/// On failure the caller receives `error.SchemaVersionAhead` and
/// `db_version`/`embedded_max` are returned via the out-parameters so
/// the CLI layer can compose a human-readable message without re-querying.
pub fn assertSchemaCompatible(
    db: *sqlite.Db,
    out_db_version: *u32,
    out_embedded_max: *u32,
) Error!void {
    try validateEmbeddedMigrations();
    const db_version: u32 = if (db.intQuery(
        "select coalesce(max(version), 0) from schema_migrations",
    )) |v| @intCast(v) else |_| 0;

    out_db_version.* = db_version;
    out_embedded_max.* = embedded_max;

    if (db_version > embedded_max) return Error.SchemaVersionAhead;
    if (db_version > 0) {
        const applied_count: u32 = @intCast(db.intQuery(
            "select count(*) from schema_migrations",
        ) catch return Error.SchemaVersionGap);
        if (applied_count != db_version) return Error.SchemaVersionGap;
    }
}

/// Run every down migration in reverse version order. After completion
/// the schema_migrations table itself is dropped (foundation migration's
/// down) — the DB is back to bare SQLite.
pub fn rollbackAll(db: *sqlite.Db, alloc: std.mem.Allocator) !void {
    var i: usize = migrations.all.len;
    while (i > 0) : (i -= 1) {
        try db.execSlice(alloc, migrations.all[i - 1].down);
    }
}

test "up applies every migration" {
    var db = try sqlite.Db.openMemory();
    defer db.close();
    try applyAll(&db, std.testing.allocator);
    const expected: i64 = @intCast(migrations.all.len);
    try std.testing.expectEqual(
        expected,
        try db.intQuery("select count(*) from schema_migrations"),
    );
}

test "up then down leaves no schema_migrations table" {
    var db = try sqlite.Db.openMemory();
    defer db.close();
    try applyAll(&db, std.testing.allocator);
    try rollbackAll(&db, std.testing.allocator);
    try std.testing.expectError(
        error.PrepareFailed,
        db.intQuery("select count(*) from schema_migrations"),
    );
}

test "up/down/up roundtrip succeeds" {
    var db = try sqlite.Db.openMemory();
    defer db.close();
    try applyAll(&db, std.testing.allocator);
    try rollbackAll(&db, std.testing.allocator);
    try applyAll(&db, std.testing.allocator);
    const expected: i64 = @intCast(migrations.all.len);
    try std.testing.expectEqual(
        expected,
        try db.intQuery("select count(*) from schema_migrations"),
    );
}

test "applyAll is idempotent — second invocation is a no-op" {
    var db = try sqlite.Db.openMemory();
    defer db.close();
    try applyAll(&db, std.testing.allocator);
    // Second call must NOT re-run any migration (would fail with
    // "table already exists" otherwise).
    try applyAll(&db, std.testing.allocator);
    const expected: i64 = @intCast(migrations.all.len);
    try std.testing.expectEqual(
        expected,
        try db.intQuery("select count(*) from schema_migrations"),
    );
}

// ---- assertSchemaCompatible tests ----

test "schema-version guard — normal case: fully migrated DB does not trip guard" {
    var db = try sqlite.Db.openMemory();
    defer db.close();
    try applyAll(&db, std.testing.allocator);

    var db_ver: u32 = 0;
    var emb: u32 = 0;
    // Guard must not fire when DB version == embedded_max.
    try assertSchemaCompatible(&db, &db_ver, &emb);
    try std.testing.expectEqual(embedded_max, db_ver);
    try std.testing.expectEqual(embedded_max, emb);
}

test "schema-version guard — fires when DB version exceeds embedded max" {
    var db = try sqlite.Db.openMemory();
    defer db.close();
    try applyAll(&db, std.testing.allocator);

    // Synthetically inject a future migration row.
    const future: u32 = embedded_max + 1;
    var buf: [128]u8 = undefined;
    const sql = try std.fmt.bufPrintZ(
        &buf,
        "insert into schema_migrations (version, description) values ({d}, 'synthetic future')",
        .{future},
    );
    try db.exec(sql);

    var db_ver: u32 = 0;
    var emb: u32 = 0;
    const result = assertSchemaCompatible(&db, &db_ver, &emb);
    try std.testing.expectError(error.SchemaVersionAhead, result);
    // Out-params must carry both sides so the caller can compose a message.
    try std.testing.expectEqual(future, db_ver);
    try std.testing.expectEqual(embedded_max, emb);
}

test "schema-version guard — fresh DB (no schema_migrations table) does not trip guard" {
    var db = try sqlite.Db.openMemory();
    defer db.close();
    // No migrations applied — table does not exist.

    var db_ver: u32 = 0;
    var emb: u32 = 0;
    // Must not fire: fresh DB maps to version=0, 0 <= embedded_max.
    try assertSchemaCompatible(&db, &db_ver, &emb);
    try std.testing.expectEqual(@as(u32, 0), db_ver);
    try std.testing.expectEqual(embedded_max, emb);
}

test "schema-version guard — DB at version below embedded max does not trip guard" {
    if (embedded_max < 2) return error.SkipZigTest; // not enough migrations to test this

    var db = try sqlite.Db.openMemory();
    defer db.close();
    try applyAll(&db, std.testing.allocator);
    // Roll back the last migration so the DB is one version behind.
    const last = migrations.all[migrations.all.len - 1];
    try db.execSlice(std.testing.allocator, last.down);

    var db_ver: u32 = 0;
    var emb: u32 = 0;
    // Guard must not fire; a forward migration would re-apply the pending one.
    try assertSchemaCompatible(&db, &db_ver, &emb);
    try std.testing.expect(db_ver < emb);
}
