--[[ @meta
name: dispatch
description: Deterministic orchestrator dispatch phases — select + claim + brief + route + cap. The caller (orchestrator agent) owns spawn + judgment; this workflow owns the deterministic phases between spawns.
phases: prep, route, heartbeat
seam: planar plan next --json, planar-agent pull/complete/fail/block, planar run start/event/finish, ctx.recommend_strategy, ctx.brief
--]]

-- dispatch.lua — deterministic orchestrator dispatch phases (plan 638 M2).
--
-- This workflow implements the DETERMINISTIC phases the orchestrator agent calls
-- BETWEEN spawns. It does NOT spawn coders or reviewers — that is the caller's
-- job. The three phases are:
--
--   prep       — select next task + acquire claim + compute strategy + compile
--                brief + open trace run. HANDS BACK: the caller spawns the coder.
--   route      — apply reviewer verdict: enforce iteration cap, execute exactly
--                ONE atomic terminal verb (complete/fail/block), or signal
--                loop-back for request-changes. Emits trace event.
--   heartbeat  — extend the claim lease during a long caller spawn.
--
-- ## Hand-back boundary (D7)
--
-- planar-execute is spawn-free by construction (D5/D7). This workflow hands
-- control back to the orchestrator agent after prep, which owns the actual
-- coder/reviewer spawning. The workflow is the deterministic scaffolding AROUND
-- those spawns — it never initiates them.
--
-- ## Claim ritual
--
-- The claim ritual follows the canonical sequence:
--   planar-agent pull <plan_id> --role coder --json
--     → claim_token + task.id (atomic: task → doing, claim → active)
--   [caller spawns coder; heartbeat as needed via the heartbeat phase]
--   planar-agent complete/fail/block --claim <token> ...
--     → atomic terminal verb (task + claim in one transaction)
--
-- NEVER split into `planar task done` + `planar-agent release` — the atomic
-- terminal verb is the whole point (claim + task status in one txn).
--
-- ## plan next JSON shape
--
-- `planar plan next <plan_id> --json` returns:
--   { plan_id, available:[{id,title,status,...}], claimed:[], stale:[], blocked:[], summary:{...} }
-- When available is an empty array, there is no work to do.
--
-- ## planar-agent pull JSON shape
--
-- `planar-agent pull <plan_id> --role coder --json` returns:
--   { ok, no_work, claim_token, claim:{...}, task:{id,status,...}, action_id }
-- The task id is at pull_result.task.id and the token at pull_result.claim_token.
--
-- ## Iteration cap
--
-- At iteration >= 5 a `request-changes` verdict is INVALID and is treated as
-- `abort` (terminal verb: fail). This enforces the methodology.md cap.
--
-- ## Trace runs
--
-- prep opens a run record (planar run start) for the dispatch cycle and emits
-- a "prep" event. route emits a "route" event and finishes the run.
-- The run_uid is auto-generated by `planar run start --json`.
--
-- ## --args contracts
--
-- prep:      { plan_id (int, required) }
-- route:     { claim_token (str, required), verdict (str, required),
--              iteration (int, required), blocker (str, optional),
--              run_uid (str, optional) }
--              verdict ∈ approve | request-changes | open-question | abort
-- heartbeat: { claim_token (str, required), ttl (int, optional) }

-- ---------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------

--- require_arg(name) — fail loudly if ctx.args[name] is nil
local function require_arg(name)
  local v = ctx.args[name]
  if v == nil then
    flow.fail("dispatch.lua: missing required ctx.args field: " .. name)
  end
  return v
end

--- tostr(v) — coerce to string for CLI argv
local function tostr(v)
  return tostring(v)
end

-- ---------------------------------------------------------------------------
-- Phase: prep
--
-- 1. Read claim-aware work queue via planar plan next --json.
--    Shape: { plan_id, available:[{id,...}], claimed:[], ... }
--    Nothing to do when #available == 0.
-- 2. If nothing available, return {available=false} immediately.
-- 3. Acquire the lease atomically via planar-agent pull --role coder --json.
--    Shape: { ok, no_work, claim_token, claim:{...}, task:{id,...}, action_id }
-- 4. Compute recommend_strategy for the plan.
-- 5. Compile the coder brief via ctx.brief.
-- 6. Open a trace run record (run_uid auto-generated by the server).
-- 7. flow.result with task_id, claim_token, brief, strategy, run_uid.
--    HAND BACK — the caller spawns the coder.
-- ---------------------------------------------------------------------------
function prep()
  flow.phase("prep")
  flow.log("dispatch.lua/prep: starting")

  local plan_id = require_arg("plan_id")

  -- 1. Read claim-aware work queue.
  -- plan next --json shape: { plan_id, available:[tasks], claimed:[], ... }
  flow.log("dispatch.lua/prep: reading plan next for plan " .. tostr(plan_id))
  local next_info = cli.planar_json({"plan", "next", tostr(plan_id), "--json"})

  -- Determine if work is available (available is an array of task objects).
  local has_work = false
  if type(next_info) == "table"
      and type(next_info.available) == "table"
      and #next_info.available > 0 then
    has_work = true
  end

  if not has_work then
    flow.log("dispatch.lua/prep: no tasks available for plan " .. tostr(plan_id))
    flow.result({ available = false, plan_id = plan_id })
    return
  end

  -- 2. Acquire claim atomically via planar-agent pull.
  --    This is the only correct entry point: pull transitions task → doing
  --    and claim → active in a single transaction.
  --    pull --json shape: { ok, no_work, claim_token, claim:{...}, task:{id,...}, action_id }
  flow.log("dispatch.lua/prep: acquiring claim via planar-agent pull")
  local pull_result = cli.planar_agent_json({
    "pull", tostr(plan_id),
    "--role", "coder",
    "--json",
  })

  -- pull may return no_work if the queue was empty or all tasks claimed.
  if type(pull_result) == "table" and pull_result.no_work then
    flow.log("dispatch.lua/prep: planar-agent pull returned no_work=true")
    flow.result({ available = false, plan_id = plan_id })
    return
  end

  -- Extract claim_token and task.id from the pull response.
  local claim_token = pull_result.claim_token
  local task_id
  if type(pull_result.task) == "table" then
    task_id = pull_result.task.id
  end
  if task_id == nil then
    -- Fallback: try claim.entity_id if task field is missing.
    if type(pull_result.claim) == "table" then
      task_id = pull_result.claim.entity_id
    end
  end

  if claim_token == nil or task_id == nil then
    flow.fail("dispatch.lua/prep: planar-agent pull did not return claim_token and task id"
      .. " (claim_token=" .. tostr(claim_token) .. " task_id=" .. tostr(task_id) .. ")")
    return
  end

  flow.log("dispatch.lua/prep: claimed task " .. tostr(task_id)
    .. " with token " .. tostr(claim_token))

  -- 3. Compute dispatch strategy for the plan.
  flow.log("dispatch.lua/prep: computing strategy for plan " .. tostr(plan_id))
  local strategy = ctx.recommend_strategy(plan_id)

  -- 4. Compile the coder brief.
  flow.log("dispatch.lua/prep: compiling brief for task " .. tostr(task_id))
  local brief_text = ctx.brief({
    plan_id           = plan_id,
    task_id           = task_id,
    claim_token       = tostr(claim_token),
    problem_statement = "Implement task " .. tostr(task_id)
      .. " on plan " .. tostr(plan_id),
    gates             = {
      "make fmt-check",
      "make build",
      "make test",
      "make test-integration (twice)",
    },
  })

  -- 5. Open trace run for this dispatch cycle.
  --    run start auto-generates the run_uid (returned in JSON).
  local run_uid = nil
  local ok_run, run_result = pcall(function()
    return cli.planar_json({
      "run", "start",
      "--plan", tostr(plan_id),
      "--workflow", "dispatch",
      "--json",
    })
  end)
  if ok_run and type(run_result) == "table" and run_result.run_uid ~= nil then
    run_uid = run_result.run_uid
    flow.log("dispatch.lua/prep: opened trace run " .. tostr(run_uid))

    -- Emit a prep event on the run.
    local ok_ev, ev_err = pcall(function()
      cli.planar({
        "run", "event", tostr(run_uid),
        "--kind", "prep",
        "--payload", "{\"task_id\":" .. tostr(task_id) .. "}",
      })
    end)
    if not ok_ev then
      flow.log("dispatch.lua/prep: WARNING: run event failed (non-fatal): " .. tostr(ev_err))
    end
  else
    flow.log("dispatch.lua/prep: WARNING: run start failed (non-fatal): " .. tostr(run_result))
  end

  -- 6. Hand back. The caller spawns the coder.
  flow.log("dispatch.lua/prep: ready — handing back to caller (spawn coder)")
  flow.result({
    available    = true,
    plan_id      = plan_id,
    task_id      = task_id,
    claim_token  = tostr(claim_token),
    brief        = brief_text,
    strategy     = strategy,
    run_uid      = run_uid,
  })
end

-- ---------------------------------------------------------------------------
-- Phase: route
--
-- Apply the reviewer's verdict for the current iteration:
--
--   approve          → planar-agent complete --claim <token>  (task→done, claim→completed)
--   abort            → planar-agent fail --claim <token>      (task→todo, claim→aborted)
--   open-question    → planar-agent block --claim <token> --blocker <id>  (task→blocked)
--   request-changes  → if iteration < 5: loop-back (NO terminal verb; signal caller)
--                      if iteration >= 5: forced abort (planar-agent fail)
--
-- INVARIANT: exactly ONE atomic terminal verb per non-loop-back path.
-- NEVER: planar task status-update + planar-agent release (strands the claim on crash).
-- ---------------------------------------------------------------------------
function route()
  flow.phase("route")
  flow.log("dispatch.lua/route: starting")

  local claim_token = require_arg("claim_token")
  local verdict     = require_arg("verdict")
  local iteration   = require_arg("iteration")
  local blocker     = ctx.args.blocker  -- optional; required for open-question
  local run_uid     = ctx.args.run_uid  -- optional; for trace

  flow.log("dispatch.lua/route: verdict=" .. tostr(verdict)
    .. " iteration=" .. tostr(iteration)
    .. " claim=" .. tostr(claim_token))

  -- Validate verdict is in the closed set.
  local valid_verdicts = {
    approve = true,
    ["request-changes"] = true,
    ["open-question"] = true,
    abort = true,
  }
  if not valid_verdicts[verdict] then
    flow.fail("dispatch.lua/route: unknown verdict '" .. tostr(verdict)
      .. "'; must be one of: approve, request-changes, open-question, abort")
    return
  end

  -- Enforce iteration cap: request-changes at iteration >= 5 is forced abort.
  local cap_fired = false
  if verdict == "request-changes" and iteration >= 5 then
    flow.log("dispatch.lua/route: iteration cap fired (iteration=" .. tostr(iteration)
      .. " >= 5); treating request-changes as abort")
    verdict   = "abort"
    cap_fired = true
  end

  local action        = nil  -- what we did
  local terminal_verb = nil  -- the planar-agent verb invoked (nil = loop-back)

  if verdict == "approve" then
    -- Atomic terminal: task → done, claim → completed.
    -- ONE verb, ONE transaction. Never task status-update + release separately.
    action        = "complete"
    terminal_verb = "complete"
    flow.log("dispatch.lua/route: invoking planar-agent complete --claim " .. tostr(claim_token))
    cli.planar_agent({
      "complete",
      "--claim", tostr(claim_token),
      "--summary", "reviewer approved at iteration " .. tostr(iteration),
    })

  elseif verdict == "abort" then
    -- Atomic terminal: task → todo, claim → aborted.
    action        = "fail"
    terminal_verb = "fail"
    local reason
    if cap_fired then
      reason = "iteration cap: request-changes at iteration " .. tostr(iteration)
    else
      reason = "reviewer abort at iteration " .. tostr(iteration)
    end
    flow.log("dispatch.lua/route: invoking planar-agent fail --claim " .. tostr(claim_token))
    cli.planar_agent({
      "fail",
      "--claim", tostr(claim_token),
      "--reason", reason,
    })

  elseif verdict == "open-question" then
    -- Atomic terminal: task → blocked, claim → released.
    action        = "block"
    terminal_verb = "block"
    if blocker == nil then
      flow.fail("dispatch.lua/route: open-question verdict requires ctx.args.blocker")
      return
    end
    flow.log("dispatch.lua/route: invoking planar-agent block --claim " .. tostr(claim_token))
    cli.planar_agent({
      "block",
      "--claim", tostr(claim_token),
      "--blocker", tostr(blocker),
    })

  elseif verdict == "request-changes" then
    -- Loop-back: NO terminal verb. Signal caller to re-spawn coder.
    -- The claim stays live; the caller must heartbeat it between iterations.
    action        = "loop-back"
    terminal_verb = nil
    flow.log("dispatch.lua/route: loop-back — caller must re-spawn coder (claim stays live)")
  end

  -- Emit trace event on the run (if run_uid is available).
  if run_uid ~= nil then
    local payload = "{\"verdict\":\"" .. tostr(verdict) .. "\""
      .. ",\"action\":\"" .. tostr(action) .. "\""
      .. ",\"iteration\":" .. tostr(iteration) .. "}"
    local ok_ev, ev_err = pcall(function()
      cli.planar({
        "run", "event", tostr(run_uid),
        "--kind", "route",
        "--payload", payload,
      })
    end)
    if not ok_ev then
      flow.log("dispatch.lua/route: WARNING: run event failed (non-fatal): " .. tostr(ev_err))
    end

    -- Close the run record on terminal paths.
    if terminal_verb ~= nil then
      local run_status
      if verdict == "approve" then
        run_status = "completed"
      else
        run_status = "failed"
      end
      local ok_fin, fin_err = pcall(function()
        cli.planar({
          "run", "finish", tostr(run_uid),
          "--status", run_status,
        })
      end)
      if not ok_fin then
        flow.log("dispatch.lua/route: WARNING: run finish failed (non-fatal): " .. tostr(fin_err))
      end
    end
  end

  flow.result({
    action        = action,
    terminal_verb = terminal_verb,
    verdict       = verdict,
    iteration     = iteration,
    cap_fired     = cap_fired,
    claim_token   = tostr(claim_token),
  })
end

-- ---------------------------------------------------------------------------
-- Phase: heartbeat
--
-- Extend the claim lease for the caller during a long coder spawn.
-- Args: { claim_token (str, required), ttl (int, optional) }
-- ---------------------------------------------------------------------------
function heartbeat()
  flow.phase("heartbeat")

  local claim_token = require_arg("claim_token")
  local ttl         = ctx.args.ttl  -- optional

  local argv = {"heartbeat", "--claim", tostr(claim_token)}
  if ttl ~= nil then
    argv[#argv + 1] = "--ttl"
    argv[#argv + 1] = tostr(ttl)
  end

  flow.log("dispatch.lua/heartbeat: extending lease for claim " .. tostr(claim_token))
  cli.planar_agent(argv)

  flow.result({ ok = true, claim_token = tostr(claim_token) })
end
