/// @file docs.cppm
/// @brief `planar.cmd.planar.docs` — the `planar` binary's per-command examples and
/// exit codes, supplied as data beside its summary table.
///
/// `CLI::App` has no slot for either, so they live here and reach two
/// consumers: `planar.cliapp.schema::schema_json` emits them as each leaf's
/// `docs.examples` and `docs.exitCodes`, and `install_docs_footers` renders
/// them as the `Examples:` and `Exit codes:` sections of that leaf's
/// `--help`. One table feeds both, so the two cannot drift. Only leaf verbs
/// have rows. Each leaf lists the exit codes its handler can return: the
/// binary-wide meaning of a code is in `k_meanings`, and a verb whose code
/// means something narrower overrides it in `k_overrides`.
module;

export module planar.cmd.planar.docs;

import std;
import planar.cliapp.schema;

namespace planar::cmd {

/// @brief The examples and exit codes of every `planar` leaf verb.
///
/// The returned table borrows static storage and is valid for the life of
/// the process.
/// @return The table.
export auto surface_docs() -> const cliapp::command_docs& {
  static constexpr std::pair<std::string_view, std::string_view> k_examples[] = {
      {"planar init", R"(planar init --name my-project)"},
      {"planar init", R"(planar init --name my-project --slug my-project --allow-no-repo)"},
      {"planar scope show", R"(planar scope show)"},
      {"planar scope show", R"(planar scope show --json)"},
      {"planar scope suggest", R"(planar scope suggest)"},
      {"planar assoc list", R"(planar assoc list)"},
      {"planar assoc list", R"(planar assoc list --kind org --json)"},
      {"planar assoc create", R"(planar assoc create acme --name Acme --kind org)"},
      {"planar assoc add", R"(planar assoc add acme my-repo)"},
      {"planar assoc remove", R"(planar assoc remove acme my-repo)"},
      {"planar assoc members", R"(planar assoc members acme)"},
      {"planar assoc detect", R"(planar assoc detect)"},
      {"planar assoc detect", R"(planar assoc detect --apply)"},
      {"planar plan create", R"(planar plan create "Add retry logic")"},
      {"planar plan create", R"(planar plan create "Add retry logic" --summary "Retry transient failures" --slug retry-logic)"},
      {"planar plan show", R"(planar plan show 7)"},
      {"planar plan show", R"(planar plan show 7 --json)"},
      {"planar plan list", R"(planar plan list)"},
      {"planar plan list", R"(planar plan list --status active --json)"},
      {"planar plan update", R"(planar plan update 7 --status active)"},
      {"planar plan update", R"(planar plan update 7 --title "Add retry logic" --summary "Retry transient failures")"},
      {"planar plan edit", R"(planar plan edit 7)"},
      {"planar plan view", R"(planar plan view 7)"},
      {"planar plan diff", R"(planar plan diff 7)"},
      {"planar plan review", R"(planar plan review 7 --approve)"},
      {"planar plan link", R"(planar plan link 7 task:42 --relationship addresses)"},
      {"planar plan next", R"(planar plan next 7)"},
      {"planar plan next", R"(planar plan next 7 --include-claimed --json)"},
      {"planar plan recommend-strategy", R"(planar plan recommend-strategy 7)"},
      {"planar plan divergence", R"(planar plan divergence 7)"},
      {"planar plan recompute-status", R"(planar plan recompute-status --plan 7)"},
      {"planar plan recompute-status", R"(planar plan recompute-status --all)"},
      {"planar plan closeout", R"(planar plan closeout 7 --dry-run)"},
      {"planar plan closeout", R"(planar plan closeout 7)"},
      {"planar plan step add", R"(planar plan step add 7 "Write the migration")"},
      {"planar plan step list", R"(planar plan step list 7)"},
      {"planar plan step done", R"(planar plan step done 3)"},
      {"planar plan step skip", R"(planar plan step skip 3)"},
      {"planar plan step link", R"(planar plan step link 3 42)"},
      {"planar plan descendants", R"(planar plan descendants 7 --json)"},
      {"planar task add", R"(planar task add "Write the migration" --plan 7)"},
      {"planar task add", R"(planar task add "Write the migration" --plan 7 --priority 2 --next-action "Draft the up file")"},
      {"planar task show", R"(planar task show 42)"},
      {"planar task show", R"(planar task show 42 --json)"},
      {"planar task packet", R"(planar task packet 42 --json)"},
      {"planar task list", R"(planar task list --plan 7)"},
      {"planar task list", R"(planar task list --status todo --json)"},
      {"planar task update", R"(planar task update 42 --status doing)"},
      {"planar task update", R"(planar task update 42 --title "Write the migration" --priority 1)"},
      {"planar task edit", R"(planar task edit 42)"},
      {"planar task view", R"(planar task view 42)"},
      {"planar task diff", R"(planar task diff 42)"},
      {"planar task review", R"(planar task review 42 --approve)"},
      {"planar task done", R"(planar task done 42)"},
      {"planar task cancel", R"(planar task cancel 42)"},
      {"planar task block", R"(planar task block 42 --on 43 --reason "Waiting on the schema change")"},
      {"planar task link", R"(planar task link 42 decision:15 --relationship depends-on)"},
      {"planar task reopen", R"(planar task reopen 42 --reason "Regression found")"},
      {"planar task touches add", R"(planar task touches add 42 my-repo --path src/engine)"},
      {"planar task touches infer", R"(planar task touches infer 42)"},
      {"planar task touches infer", R"(planar task touches infer 42 --apply)"},
      {"planar task touches list", R"(planar task touches list 42)"},
      {"planar task touches remove", R"(planar task touches remove 42 my-repo)"},
      {"planar task facts stage", R"(planar task facts stage 42)"},
      {"planar question add", R"(planar question add "Which retry budget do we want?" --plan 7)"},
      {"planar question edit", R"(planar question edit 12)"},
      {"planar question view", R"(planar question view 12)"},
      {"planar question diff", R"(planar question diff 12)"},
      {"planar question review", R"(planar question review 12 --approve)"},
      {"planar question answer", R"(planar question answer 12 --answer "Three attempts")"},
      {"planar question wontfix", R"(planar question wontfix 12 --reason "Out of scope")"},
      {"planar question list", R"(planar question list --status open)"},
      {"planar question list", R"(planar question list --plan 7 --json)"},
      {"planar question show", R"(planar question show 12)"},
      {"planar question link", R"(planar question link 12 task:42 --relationship addresses)"},
      {"planar scenario add", R"(planar scenario add "Retry succeeds on the second attempt" --plan 7)"},
      {"planar scenario edit", R"(planar scenario edit 9)"},
      {"planar scenario view", R"(planar scenario view 9)"},
      {"planar scenario diff", R"(planar scenario diff 9)"},
      {"planar scenario review", R"(planar scenario review 9 --approve)"},
      {"planar scenario verify", R"(planar scenario verify 9 --outcome pass --summary "Passed on the first run")"},
      {"planar scenario retire", R"(planar scenario retire 9 --reason "Superseded")"},
      {"planar scenario list", R"(planar scenario list --related 42)"},
      {"planar scenario list", R"(planar scenario list --status ready --json)"},
      {"planar scenario show", R"(planar scenario show 9)"},
      {"planar scenario link", R"(planar scenario link 9 task:42 --relationship verifies)"},
      {"planar decision add",
       R"(planar decision add "Use exponential backoff" --body "Back off exponentially between attempts" --rationale "Avoids retry storms" --plan 7)"},
      {"planar decision show", R"(planar decision show 15)"},
      {"planar decision list", R"(planar decision list --status accepted)"},
      {"planar decision list", R"(planar decision list --plan 7 --json)"},
      {"planar decision accept", R"(planar decision accept 15)"},
      {"planar decision supersede", R"(planar decision supersede 15 --by 16)"},
      {"planar decision withdraw", R"(planar decision withdraw 15)"},
      {"planar decision edit", R"(planar decision edit 15)"},
      {"planar decision view", R"(planar decision view 15)"},
      {"planar decision diff", R"(planar decision diff 15)"},
      {"planar decision review", R"(planar decision review 15 --approve)"},
      {"planar decision link", R"(planar decision link 15 plan:7 --relationship derives-from)"},
      {"planar artifact add", R"(planar artifact add "Retry design" --kind tech_spec --body "One paragraph")"},
      {"planar artifact add", R"(planar artifact add "Retry design" --kind tech_spec --from-file docs/retry.md --plan 7)"},
      {"planar artifact show", R"(planar artifact show 20)"},
      {"planar artifact list", R"(planar artifact list --kind tech_spec)"},
      {"planar artifact list", R"(planar artifact list --plan 7 --json)"},
      {"planar artifact update", R"(planar artifact update 20 --body @docs/retry.md)"},
      {"planar artifact update", R"(planar artifact update 20 --status active)"},
      {"planar artifact edit", R"(planar artifact edit 20)"},
      {"planar artifact view", R"(planar artifact view 20)"},
      {"planar artifact diff", R"(planar artifact diff 20)"},
      {"planar artifact review", R"(planar artifact review 20 --approve)"},
      {"planar artifact link", R"(planar artifact link 20 plan:7 --relationship derives-from)"},
      {"planar document project", R"(planar document project --kind artifact --id 20 --json)"},
      {"planar document validate-range",
       R"(planar document validate-range --kind artifact --id 20 --content-revision rev-1 --start-key k1 --start-offset 0 --end-key k1 --end-offset 4 --json)"},
      {"planar annotate add",
       R"(planar annotate add --anchor-path src/engine/retry.cpp --line-start 10 --line-end 14 --title "Check the backoff cap" --task 42)"},
      {"planar annotate show", R"(planar annotate show 31)"},
      {"planar annotate list", R"(planar annotate list --task 42)"},
      {"planar annotate list", R"(planar annotate list --status active --json)"},
      {"planar annotate capabilities", R"(planar annotate capabilities)"},
      {"planar annotate update", R"(planar annotate update 31 --title "Backoff cap confirmed")"},
      {"planar annotate remove", R"(planar annotate remove 31 --expected-revision 2)"},
      {"planar annotate tag", R"(planar annotate tag 31 needs-review)"},
      {"planar annotate tag", R"(planar annotate tag 31 needs-review --remove)"},
      {"planar annotate resolve", R"(planar annotate resolve 31)"},
      {"planar annotate dismiss", R"(planar annotate dismiss 31)"},
      {"planar annotate archive", R"(planar annotate archive 31)"},
      {"planar annotate bulk-resolve", R"(planar annotate bulk-resolve --operation-id op-1 --task 42)"},
      {"planar annotate bulk-dismiss", R"(planar annotate bulk-dismiss --operation-id op-2 --anchor-path src/engine/retry.cpp)"},
      {"planar annotate bulk-archive", R"(planar annotate bulk-archive --operation-id op-3 --plan 7)"},
      {"planar annotate verify", R"(planar annotate verify --anchor-path src/engine/retry.cpp)"},
      {"planar annotate sweep", R"(planar annotate sweep --since-days 30)"},
      {"planar annotate command", R"(planar annotate command --request @-)"},
      {"planar annotate receipt",
       R"(planar annotate receipt --source-uuid 6f1c2d3e-0000-4000-8000-000000000001 --operation-id op-1)"},
      {"planar promote", R"(planar promote task:42 --to assoc:acme)"},
      {"planar demote", R"(planar demote task:42)"},
      {"planar workbench lint", R"(planar workbench lint 7)"},
      {"planar workbench lint", R"(planar workbench lint --all)"},
      {"planar workbench pull", R"(planar workbench pull 7)"},
      {"planar workbench push", R"(planar workbench push 7)"},
      {"planar workbench status", R"(planar workbench status 7)"},
      {"planar workbench status", R"(planar workbench status --verbose)"},
      {"planar workbench resolve", R"(planar workbench resolve 5 --prefer fs)"},
      {"planar workbench sync", R"(planar workbench sync 7)"},
      {"planar workbench archive", R"(planar workbench archive 7)"},
      {"planar workbench restore", R"(planar workbench restore 7)"},
      {"planar workbench gc", R"(planar workbench gc 7 --dry-run)"},
      {"planar workbench gc", R"(planar workbench gc --all-scopes --yes)"},
      {"planar workbench list", R"(planar workbench list)"},
      {"planar workbench list", R"(planar workbench list --json)"},
      {"planar workbench publish", R"(planar workbench publish 7 --system github-main)"},
      {"planar workbench extract-questions", R"(planar workbench extract-questions 7)"},
      {"planar workbench edit", R"(planar workbench edit 7 --editor vim)"},
      {"planar workspace init", R"(planar workspace init --name acme --slug acme)"},
      {"planar workspace doctor", R"(planar workspace doctor)"},
      {"planar workspace routing build", R"(planar workspace routing build)"},
      {"planar workspace routing show", R"(planar workspace routing show --json)"},
      {"planar workspace regenerate", R"(planar workspace regenerate)"},
      {"planar link", R"(planar link task:42 --to github-main:456 --role tracks)"},
      {"planar link", R"(planar link plan:7 --to github-main:123 --sync push)"},
      {"planar unlink", R"(planar unlink 4)"},
      {"planar links add", R"(planar links add task:42 plan:7 --relationship depends-on)"},
      {"planar links list", R"(planar links list task:42)"},
      {"planar links list", R"(planar links list task:42 --json)"},
      {"planar links remove", R"(planar links remove 4)"},
      {"planar links trail", R"(planar links trail 4)"},
      {"planar resume validate", R"(planar resume validate 42)"},
      {"planar handoff create", R"(planar handoff create 8 --vendor claude)"},
      {"planar handoff validate", R"(planar handoff validate 6)"},
      {"planar handoff consume", R"(planar handoff consume 6 --vendor claude)"},
      {"planar handoff abandon", R"(planar handoff abandon 6 --reason "Superseded by a newer handoff")"},
      {"planar handoff list", R"(planar handoff list --status pending)"},
      {"planar handoff show", R"(planar handoff show 6)"},
      {"planar capture session", R"(planar capture session --vendor claude --task 42)"},
      {"planar capture commits", R"(planar capture commits --since HEAD~5)"},
      {"planar capture end", R"(planar capture end --summary "Landed the migration")"},
      {"planar capture note", R"(planar capture note "Backoff cap is 30 seconds")"},
      {"planar capture command", R"(planar capture command "make test" --outcome pass)"},
      {"planar capture file", R"(planar capture file src/engine/retry.cpp --role edited)"},
      {"planar capture snapshot",
       R"(planar capture snapshot "Mid-way through the migration" --task 42 --next-action "Run the roundtrip test")"},
      {"planar audit trail", R"(planar audit trail 42)"},
      {"planar audit trail", R"(planar audit trail --link 4)"},
      {"planar audit commits", R"(planar audit commits --task 42 --shas)"},
      {"planar audit session", R"(planar audit session 5)"},
      {"planar audit publish-decision", R"(planar audit publish-decision 15)"},
      {"planar audit handoff-readiness", R"(planar audit handoff-readiness --threshold 80)"},
      {"planar health hygiene", R"(planar health hygiene --stale-doing 7 --json)"},
      {"planar models evals", R"(planar models evals --role coder --tier medium)"},
      {"planar models resolve", R"(planar models resolve --role coder --task 42)"},
      {"planar models experiments", R"(planar models experiments)"},
      {"planar models outcomes", R"(planar models outcomes --limit 20)"},
      {"planar models registry list", R"(planar models registry list --json)"},
      {"planar models registry add", R"(planar models registry add --vendor claude --id sonnet --order 1)"},
      {"planar models registry update", R"(planar models registry update --candidate 3 --order 2)"},
      {"planar models registry remove", R"(planar models registry remove --candidate 3)"},
      {"planar models registry bind", R"(planar models registry bind --candidate 3 --role coder --tier medium)"},
      {"planar models registry unbind", R"(planar models registry unbind --candidate 3 --role coder --tier medium)"},
      {"planar models registry observe",
       R"(planar models registry observe --candidate 3 --host devbox --version 1 --availability available --spawn-verification verified --evidence-ref artifact:20 --captured-at 2026-10-04T09:00:00Z --expires-at 2026-10-05T09:00:00Z)"},
      {"planar models registry eligibility",
       R"(planar models registry eligibility --candidate 3 --host devbox --role coder --tier medium --now 2026-10-04T09:00:00Z)"},
      {"planar models registry verify-identity",
       R"(planar models registry verify-identity --candidate 3 --actual-vendor claude --actual-id sonnet)"},
      {"planar models registry export", R"(planar models registry export)"},
      {"planar dashboard", R"(planar dashboard)"},
      {"planar dashboard", R"(planar dashboard --agents)"},
      {"planar spec ingest", R"(planar spec ingest retry-logic)"},
      {"planar spec ingest", R"(planar spec ingest retry-logic --apply)"},
      {"planar test-spec status", R"(planar test-spec status 7)"},
      {"planar config show", R"(planar config show --effective)"},
      {"planar config show", R"(planar config show --raw --format json)"},
      {"planar config edit", R"(planar config edit)"},
      {"planar config validate", R"(planar config validate)"},
      {"planar config init", R"(planar config init)"},
      {"planar config path", R"(planar config path)"},
      {"planar templates list", R"(planar templates list --system github)"},
      {"planar templates show", R"(planar templates show default github task)"},
      {"planar templates render", R"(planar templates render default github task --entity task:42)"},
      {"planar templates validate", R"(planar templates validate default github task)"},
      {"planar templates init", R"(planar templates init)"},
      {"planar templates path", R"(planar templates path --system github)"},
      {"planar tree", R"(planar tree --depth 2)"},
      {"planar tree", R"(planar tree --kind task --status todo)"},
      {"planar search", R"(planar search "retry logic")"},
      {"planar search", R"(planar search retry --kind task --limit 10)"},
      {"planar local list", R"(planar local list --vendor claude)"},
      {"planar local link", R"(planar local link my-skill --dry-run)"},
      {"planar local unlink", R"(planar local unlink my-skill)"},
      {"planar local import", R"(planar local import ./my-skill.md --kind skill)"},
      {"planar local migrate", R"(planar local migrate --dry-run)"},
      {"planar skills", R"(planar skills)"},
      {"planar import", R"(planar import . --dry-run)"},
      {"planar import", R"(planar import . --apply)"},
      {"planar synthesize", R"(planar synthesize . --dry-run)"},
      {"planar report", R"(planar report --days 7)"},
      {"planar bench start", R"(planar bench start run-1a2b3c --plan 7 --arm strict --base-sha 0123abc --config-hash abc123)"},
      {"planar bench event", R"(planar bench event run-1a2b3c --kind tool_call --seq 1)"},
      {"planar bench touch", R"(planar bench touch run-1a2b3c --task 42 --path src/engine/retry.cpp --kind actual)"},
      {"planar bench harvest", R"(planar bench harvest run-1a2b3c --task 42 --worktree ../wt)"},
      {"planar bench finish", R"(planar bench finish run-1a2b3c --status completed)"},
      {"planar bench show", R"(planar bench show run-1a2b3c)"},
      {"planar closure compute", R"(planar closure compute 42)"},
      {"planar closure show", R"(planar closure show 42)"},
      {"planar run start", R"(planar run start --plan 7 --workflow build)"},
      {"planar run event", R"(planar run event run-1a2b3c --kind step_started)"},
      {"planar run finish", R"(planar run finish run-1a2b3c --status completed)"},
      {"planar run show", R"(planar run show run-1a2b3c)"},
      {"planar groups recommend", R"(planar groups recommend 7 --budget 4)"},
      {"planar explore", R"(planar explore --plan 7)"},
      {"planar explore", R"(planar explore --plain)"},
      {"planar workflow list", R"(planar workflow list)"},
      {"planar workflow show", R"(planar workflow show build)"},
      {"planar workflow run", R"(planar workflow run build --phase plan)"},
      {"planar feedback triage list", R"(planar feedback triage list --severity high)"},
      {"planar feedback triage show", R"(planar feedback triage show task:42)"},
      {"planar feedback triage set",
       R"(planar feedback triage set task:42 --severity high --disposition accepted --reproduction reproduced)"},
      {"planar update", R"(planar update --check)"},
      {"planar update", R"(planar update)"},
      {"planar update", R"(planar update --version v1.2.3)"},
  };
  static constexpr std::pair<std::string_view, std::string_view> k_exit_codes[] = {
      {"planar init", "0 1 2 7 8"},
      {"planar scope show", "0 1 2 7"},
      {"planar scope suggest", "0 1 2 7"},
      {"planar scope use", "2"},
      {"planar scope pop", "2"},
      {"planar scope clear", "2"},
      {"planar assoc list", "0 1 2 7"},
      {"planar assoc create", "0 1 2 6 7 8"},
      {"planar assoc add", "0 1 2 7 8"},
      {"planar assoc remove", "0 1 2 7 8"},
      {"planar assoc members", "0 1 2 7 8"},
      {"planar assoc detect", "0 1 2 7 8"},
      {"planar plan create", "0 1 2 6 7 8"},
      {"planar plan show", "0 1 2 7"},
      {"planar plan list", "0 1 2 7"},
      {"planar plan update", "0 1 2 6 7 8"},
      {"planar plan edit", "0 1 2 7 8"},
      {"planar plan view", "0 1 2 7"},
      {"planar plan diff", "0 1 2 7"},
      {"planar plan review", "0 1 2 7"},
      {"planar plan link", "0 1 2 7 8"},
      {"planar plan next", "0 1 2 7"},
      {"planar plan recommend-strategy", "0 1 2 7"},
      {"planar plan divergence", "0 1 2 7"},
      {"planar plan recompute-status", "0 1 2 7 8"},
      {"planar plan closeout", "0 1 2 3 7 8"},
      {"planar plan step add", "0 1 2 7 8"},
      {"planar plan step list", "0 1 2 7 8"},
      {"planar plan step done", "0 1 2 7 8"},
      {"planar plan step skip", "0 1 2 7 8"},
      {"planar plan step link", "0 1 2 7 8"},
      {"planar plan descendants", "0 1 2 7 8"},
      {"planar task add", "0 1 2 6 7 8"},
      {"planar task show", "0 1 2 7"},
      {"planar task packet", "0 1 2 7"},
      {"planar task list", "0 1 2 7"},
      {"planar task update", "0 1 2 5 6 7 8"},
      {"planar task edit", "0 1 2 7 8"},
      {"planar task view", "0 1 2 7"},
      {"planar task diff", "0 1 2 7"},
      {"planar task review", "0 1 2 7"},
      {"planar task done", "0 1 2 7 8"},
      {"planar task cancel", "0 1 2 7 8"},
      {"planar task block", "0 1 2 7 8"},
      {"planar task link", "0 1 2 7 8"},
      {"planar task reopen", "0 1 2 7 8"},
      {"planar task touches add", "0 1 2 7 8"},
      {"planar task touches infer", "0 1 2 7 8"},
      {"planar task touches list", "0 1 2 7"},
      {"planar task touches remove", "0 1 2 7 8"},
      {"planar task facts stage", "0 1 2 7 8"},
      {"planar question add", "0 1 2 7 8"},
      {"planar question edit", "0 1 2 7 8"},
      {"planar question view", "0 1 2 7"},
      {"planar question diff", "0 1 2 7"},
      {"planar question review", "0 1 2 7"},
      {"planar question answer", "0 1 2 7 8"},
      {"planar question wontfix", "0 1 2 7 8"},
      {"planar question list", "0 1 2 7"},
      {"planar question show", "0 1 2 7"},
      {"planar question link", "0 1 2 7 8"},
      {"planar scenario add", "0 1 2 7 8"},
      {"planar scenario edit", "0 1 2 7 8"},
      {"planar scenario view", "0 1 2 7"},
      {"planar scenario diff", "0 1 2 7"},
      {"planar scenario review", "0 1 2 7"},
      {"planar scenario verify", "0 1 2 7 8"},
      {"planar scenario retire", "0 1 2 7 8"},
      {"planar scenario list", "0 1 2 7"},
      {"planar scenario show", "0 1 2 7"},
      {"planar scenario link", "0 1 2 7 8"},
      {"planar decision add", "0 1 2 7 8"},
      {"planar decision show", "0 1 2 7"},
      {"planar decision list", "0 1 2 7"},
      {"planar decision accept", "0 1 2 5 7 8"},
      {"planar decision supersede", "0 1 2 7 8"},
      {"planar decision withdraw", "0 1 2 5 7 8"},
      {"planar decision edit", "0 1 2 7 8"},
      {"planar decision view", "0 1 2 7"},
      {"planar decision diff", "0 1 2 7"},
      {"planar decision review", "0 1 2 7"},
      {"planar decision link", "0 1 2 7 8"},
      {"planar artifact add", "0 1 2 7 8"},
      {"planar artifact show", "0 1 2 7"},
      {"planar artifact list", "0 1 2 7"},
      {"planar artifact update", "0 1 2 7 8"},
      {"planar artifact edit", "0 1 2 7 8"},
      {"planar artifact view", "0 1 2 7"},
      {"planar artifact diff", "0 1 2 7"},
      {"planar artifact review", "0 1 2 7"},
      {"planar artifact link", "0 1 2 7 8"},
      {"planar document project", "0 1 2 7 8"},
      {"planar document validate-range", "0 1 2 7 8"},
      {"planar annotate add", "0 1 2 6 7 8"},
      {"planar annotate show", "0 1 2 7 8"},
      {"planar annotate list", "0 1 2 7 8"},
      {"planar annotate capabilities", "0 1 2 8"},
      {"planar annotate update", "0 1 2 6 7 8"},
      {"planar annotate remove", "0 1 2 7 8"},
      {"planar annotate tag", "0 1 2 7 8"},
      {"planar annotate resolve", "0 1 2 7 8"},
      {"planar annotate dismiss", "0 1 2 7 8"},
      {"planar annotate archive", "0 1 2 7 8"},
      {"planar annotate bulk-resolve", "0 1 2 7 8"},
      {"planar annotate bulk-dismiss", "0 1 2 7 8"},
      {"planar annotate bulk-archive", "0 1 2 7 8"},
      {"planar annotate verify", "0 1 2 7 8"},
      {"planar annotate sweep", "0 1 2 7 8"},
      {"planar annotate command", "0 1 2 7 8"},
      {"planar annotate receipt", "0 1 2 7 8"},
      {"planar promote", "0 1 2 7 8"},
      {"planar demote", "0 1 2 7 8"},
      {"planar workbench lint", "0 1 2 7 8"},
      {"planar workbench pull", "0 1 2 3 7"},
      {"planar workbench push", "0 1 2 3 7"},
      {"planar workbench status", "0 1 2 7"},
      {"planar workbench resolve", "0 1 2 7"},
      {"planar workbench sync", "0 1 2 3 7"},
      {"planar workbench archive", "0 1 2 7 8"},
      {"planar workbench restore", "0 1 2 7 8"},
      {"planar workbench gc", "0 1 2 7 8"},
      {"planar workbench list", "0 1 2 7 8"},
      {"planar workbench publish", "0 1 2 3 6 7 8"},
      {"planar workbench extract-questions", "0 1 2 7 8"},
      {"planar workbench edit", "0 1 2 7 8"},
      {"planar workspace init", "0 1 2 7"},
      {"planar workspace doctor", "0 1 2 7"},
      {"planar workspace routing build", "0 1 2 7"},
      {"planar workspace routing show", "0 1 2 7"},
      {"planar workspace regenerate", "0 1 2 7"},
      {"planar link", "0 1 2 6 7 8"},
      {"planar unlink", "0 1 2 7 8"},
      {"planar links add", "0 1 2 7 8"},
      {"planar links list", "0 1 2 7 8"},
      {"planar links remove", "0 1 2 7 8"},
      {"planar links trail", "0 1 2 7 8"},
      {"planar resume validate", "0 1 2 7"},
      {"planar handoff create", "0 1 2 7"},
      {"planar handoff validate", "0 1 2 7"},
      {"planar handoff consume", "0 1 2 7"},
      {"planar handoff abandon", "0 1 2 7"},
      {"planar handoff list", "0 1 2 7"},
      {"planar handoff show", "0 1 2 7"},
      {"planar capture session", "0 1 2 7"},
      {"planar capture commits", "0 1 2 7"},
      {"planar capture end", "0 1 2 7"},
      {"planar capture note", "0 1 2 7"},
      {"planar capture command", "0 1 2 7"},
      {"planar capture file", "0 1 2 7"},
      {"planar capture snapshot", "0 1 2 7"},
      {"planar audit trail", "0 1 2 7"},
      {"planar audit commits", "0 1 2 7"},
      {"planar audit session", "0 1 2 7"},
      {"planar audit publish-decision", "0 1 2 5 7"},
      {"planar audit handoff-readiness", "0 1 2 7"},
      {"planar health hygiene", "0 1 2 7"},
      {"planar models evals", "0 1 2 7"},
      {"planar models resolve", "0 1 2 7"},
      {"planar models experiments", "0 1 2 7"},
      {"planar models outcomes", "0 1 2 7"},
      {"planar models registry list", "0 1 2 7"},
      {"planar models registry add", "0 1 2 3 7"},
      {"planar models registry update", "0 1 2 7"},
      {"planar models registry remove", "0 1 2 7"},
      {"planar models registry bind", "0 1 2 3 7"},
      {"planar models registry unbind", "0 1 2 7"},
      {"planar models registry observe", "0 1 2 3 7"},
      {"planar models registry eligibility", "0 1 2 7"},
      {"planar models registry verify-identity", "0 1 2 7"},
      {"planar models registry export", "0 1 2 7"},
      {"planar dashboard", "0 1 2 7"},
      {"planar spec ingest", "0 1 2 5 6 7 8"},
      {"planar test-spec status", "0 1 2 7"},
      {"planar config show", "0 1 2"},
      {"planar config edit", "0 1 2"},
      {"planar config validate", "0 1 2"},
      {"planar config init", "0 1 2"},
      {"planar config path", "0 1 2"},
      {"planar templates list", "0 1 2"},
      {"planar templates show", "0 1 2"},
      {"planar templates render", "0 1 2"},
      {"planar templates validate", "0 1 2"},
      {"planar templates init", "0 1 2"},
      {"planar templates path", "0 1 2"},
      {"planar tree", "0 1 2 7"},
      {"planar search", "0 1 2 7"},
      {"planar local list", "0 1 2"},
      {"planar local link", "0 1 2"},
      {"planar local unlink", "0 1 2"},
      {"planar local import", "0 1 2"},
      {"planar local migrate", "0 1 2"},
      {"planar skills", "0 1 2"},
      {"planar import", "0 1 2 7"},
      {"planar synthesize", "0 1 2 7"},
      {"planar version", "0 2"},
      {"planar completion", "0 1 2"},
      {"planar schema", "0 1 2"},
      {"planar report", "0 1 2 7"},
      {"planar bench start", "0 1 2 6 7"},
      {"planar bench event", "0 1 2 7"},
      {"planar bench touch", "0 1 2 7"},
      {"planar bench harvest", "0 1 2 7"},
      {"planar bench finish", "0 1 2 7"},
      {"planar bench show", "0 1 2 7"},
      {"planar closure compute", "0 1 2 5 7 8"},
      {"planar closure show", "0 1 2 7 8"},
      {"planar run start", "0 1 2 6 7 8"},
      {"planar run event", "0 1 2 7 8"},
      {"planar run finish", "0 1 2 7 8"},
      {"planar run show", "0 1 2 7 8"},
      {"planar groups recommend", "0 1 2 7 8"},
      {"planar explore", "0 1 2"},
      {"planar workflow list", "0 1 2"},
      {"planar workflow show", "0 1 2"},
      {"planar workflow run", "0 1 2"},
      {"planar feedback triage list", "0 1 2 7"},
      {"planar feedback triage show", "0 1 2 7"},
      {"planar feedback triage set", "0 1 2 5 7 8"},
      {"planar help", "0 2"},
      {"planar update", "0 1 2 10 130 143"},
  };
  static constexpr cliapp::exit_code_doc k_meanings[] = {
      {0, R"(Success.)"},
      {1, R"(Generic failure: entity not found, an unmapped error, or a busy source.)"},
      {2, R"(Bad input: an invalid value or entity ref, or a parse failure such as an unknown flag or a missing argument.)"},
      {3, R"(Conflict: an operational-plane or workbench conflict that needs an explicit resolve.)"},
      {5, R"(Cross-scope write refused: the entity belongs to a scope the resolved scope does not cover.)"},
      {6, R"(Precondition conflict: the slug is taken or the entity already exists.)"},
      {7, R"(The database schema is newer than this binary supports.)"},
      {8, R"(Refused: a planning verb was run from inside a git worktree.)"},
  };
  static constexpr cliapp::exit_meaning_override k_overrides[] = {
      {"planar plan closeout", 3, R"(The plan is not ready to close; the report lists the reasons (apply path only).)"},
      {"planar workbench pull", 3, R"(Workbench conflicts must be resolved before the pull can finish.)"},
      {"planar workbench push", 3, R"(Workbench conflicts must be resolved before the push can finish.)"},
      {"planar workbench sync", 3, R"(Workbench conflicts must be resolved before the sync can finish.)"},
      {"planar workbench publish", 3, R"(Workbench conflicts must be resolved before publication.)"},
      {"planar models registry add", 3, R"(The registry row conflicts with an existing one.)"},
      {"planar models registry bind", 3, R"(The registry binding conflicts with an existing one.)"},
      {"planar models registry observe", 3, R"(The host observation conflicts with an existing one.)"},
      {"planar workbench publish", 6, R"(The plan already has an external link on that system.)"},
      {"planar bench start", 6, R"(A run with that uid already exists.)"},
      {"planar run start", 6, R"(A run with that uid already exists.)"},
      {"planar update", 1, R"(A fault, a refusal, a competing owner, or an incomplete installation; nothing was installed.)"},
      {"planar update", 10, R"(--check found a release newer than the installed one.)"},
      {"planar update", 130, R"(Interrupted by SIGINT; the download directory was removed and the lock released.)"},
      {"planar update", 143, R"(Interrupted by SIGTERM; the download directory was removed and the lock released.)"},
  };
  static constexpr cliapp::command_docs k_docs{k_examples, k_exit_codes, k_meanings, k_overrides};
  return k_docs;
}

} // namespace planar::cmd
