/// @file surface.cpp
/// @brief Implementation of `planar.cmd.planar_agent.surface` — GENERATED, do not hand-edit.
///
/// Regenerate with `scripts/gen-cli-surface.py` (see that script and this
/// module's interface header for the provenance argument).

module planar.cmd.planar_agent.surface;

import std;
import planar.cliapp.surface;

namespace planar::cmd::agent {

using cliapp::flag_spec;
using cliapp::node_spec;
using cliapp::positional_spec;

namespace {

constexpr std::string_view k_path_0[]  = {"version"};
constexpr std::string_view k_path_1[]  = {"pull"};
constexpr std::string_view k_path_2[]  = {"peek"};
constexpr std::string_view k_path_3[]  = {"complete"};
constexpr std::string_view k_path_4[]  = {"fail"};
constexpr std::string_view k_path_5[]  = {"release"};
constexpr std::string_view k_path_6[]  = {"block"};
constexpr std::string_view k_path_7[]  = {"claim"};
constexpr std::string_view k_path_8[]  = {"heartbeat"};
constexpr std::string_view k_path_9[]  = {"claim-associate"};
constexpr std::string_view k_path_10[] = {"action"};
constexpr std::string_view k_path_11[] = {"ingest"};
constexpr std::string_view k_path_12[] = {"reconcile"};
constexpr std::string_view k_path_13[] = {"abort"};
constexpr std::string_view k_path_14[] = {"schema"};
constexpr std::string_view k_path_15[] = {"run"};
constexpr std::string_view k_path_16[] = {"dispatch"};
constexpr std::string_view k_path_17[] = {"context"};
constexpr std::string_view k_path_18[] = {"action", "start"};
constexpr std::string_view k_path_19[] = {"action", "end"};
constexpr std::string_view k_path_20[] = {"run", "start"};
constexpr std::string_view k_path_21[] = {"run", "end"};
constexpr std::string_view k_path_22[] = {"dispatch", "preview"};
constexpr std::string_view k_path_23[] = {"dispatch", "confirm"};
constexpr std::string_view k_path_24[] = {"context", "add"};
constexpr std::string_view k_path_25[] = {"context", "capsule"};
constexpr std::string_view k_path_26[] = {"context", "list"};
constexpr std::string_view k_path_27[] = {"context", "resolve"};

constexpr flag_spec k_flags_1[] = {
    {.name          = "--vendor",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "planar-agent",
     .description   = "Vendor tag (default: planar-agent)"},
    {.name          = "--vendor-session",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Vendor session id (e.g. claude:s1)"},
    {.name          = "--role",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Role name (planner|coder|reviewer|test_coder|...)"},
    {.name          = "--ttl",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "600",
     .description   = "Lease TTL (default 600s; accepts bare int seconds or suffixed duration: 10m, 1h, 500ms)"},
    {.name          = "--purpose",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Free-text purpose recorded on the claim"},
    {.name          = "--base-ref",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Git ref the work is based on"},
    {.name          = "--worktree",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Worktree id or path for isolation context"},
    {.name          = "--repo-root",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Absolute path of checkout to probe locality against"},
    {.name          = "--no-locality-probe",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Skip the git locality probe"},
    {.name          = "--metadata",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description =
         "Opaque text (typically JSON) persisted on the dispatch action row; validated as well-formed JSON when supplied"},
    {.name          = "--parent-action",
     .kind          = "int",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description =
         "Parent action id; wires the new action as a child of this action in `planar-watch tree` (cross-session hierarchy)"},
    {.name          = "--run",
     .kind          = "int",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "workflow_runs.id to associate with this claim (populated by an external workflow harness; omit for "
                      "interactive claims)"},
    {.name          = "--stage",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Workflow stage name (e.g. code, review) to record on the claim; requires --run"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_2[] = {
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_3[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token returned by pull/claim"},
    {.name          = "--summary",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Free-text completion summary recorded on the action"},
    {.name          = "--no-locality-probe",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Skip the git locality probe and commit collection"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_4[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token returned by pull/claim"},
    {.name          = "--reason",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Failure reason recorded on the claim and action"},
    {.name          = "--category",
     .kind          = "choice",
     .required      = false,
     .list          = false,
     .default_value = "unknown",
     .description   = "Closed failure category (default: unknown)"},
    {.name          = "--no-locality-probe",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Skip the git locality probe and commit collection"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_5[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token returned by pull/claim"},
    {.name          = "--reason",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Optional reason for releasing"},
    {.name          = "--no-locality-probe",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Skip the git locality probe and commit collection"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_6[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token returned by pull/claim"},
    {.name          = "--blocker",
     .kind          = "int",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Task id of the blocker (entity_links target)"},
    {.name          = "--reason",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Free-text reason recorded on the claim"},
    {.name          = "--no-locality-probe",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Skip the git locality probe and commit collection"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_7[] = {
    {.name          = "--entity",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Entity ref: task:<id> | plan:<id> | plan_step:<id>"},
    {.name          = "--vendor",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "planar-agent",
     .description   = "Vendor tag (default: planar-agent)"},
    {.name          = "--vendor-session",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Vendor session id (e.g. claude:s1)"},
    {.name          = "--role",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Role name (planner|coder|reviewer|test_coder|...)"},
    {.name          = "--model",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Model actually used, recorded verbatim as an opaque string. Never validated against a supported list."},
    {.name          = "--ttl",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "600",
     .description   = "Lease TTL (default 600s; accepts bare int seconds or suffixed duration: 10m, 1h, 500ms)"},
    {.name          = "--purpose",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Free-text purpose recorded on the claim"},
    {.name          = "--worktree",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Worktree id or path for isolation context"},
    {.name          = "--repo-root",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Absolute path of checkout to probe locality against"},
    {.name          = "--no-locality-probe",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Skip the git locality probe"},
    {.name          = "--no-transition",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Claim without changing task status (plan and plan_step are always unchanged)"},
    {.name          = "--force",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Take over an existing live claim (operator recovery)"},
    {.name          = "--run",
     .kind          = "int",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "workflow_runs.id to associate with this claim (populated by an external workflow harness; omit for "
                      "interactive claims)"},
    {.name          = "--stage",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Workflow stage name (e.g. code, review) to record on the claim; requires --run"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_8[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token to refresh"},
    {.name          = "--ttl",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "600",
     .description   = "New TTL (default 600s; accepts bare int seconds or suffixed duration: 10m, 1h, 500ms)"},
    {.name          = "--status",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Free-text status string recorded on the heartbeat action row's summary column"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_9[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token to associate"},
    {.name          = "--run",
     .kind          = "int",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "workflow_runs.id to stamp on the claim"},
    {.name          = "--stage",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Stage name to record (e.g. code, review); omit for NULL"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_11[] = {
    {.name          = "--vendor",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Vendor tag (claude|copilot wired; codex reserved)"},
    {.name          = "--event",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Event JSON: @<file> reads from path; @- reads from stdin"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_12[] = {
    {.name          = "--dry-run",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Report candidates without writing"},
    {.name          = "--stale-after",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "0",
     .description =
         "Additional grace beyond lease expiry (default 0s; accepts bare int seconds or suffixed duration: 10m, 1h, 500ms)"},
    {.name          = "--session",
     .kind          = "int",
     .required      = false,
     .list          = false,
     .default_value = "0",
     .description   = "Scope the sweep to a single session id (0 = global sweep, the default)"},
    {.name          = "--plan",
     .kind          = "int",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Scope the sweep to claims/actions/runs belonging to this plan id (0 or absent = global sweep)"},
    {.name          = "--category",
     .kind          = "choice",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Optional closed failure category applied to claims made stale"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_13[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token to force-release"},
    {.name          = "--reason",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Optional reason recorded on the claim and audit row"},
    {.name          = "--category",
     .kind          = "choice",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Optional closed failure category for the recovered claim"},
    {.name          = "--vendor",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "planar-agent",
     .description   = "Vendor tag for the aborting session"},
    {.name          = "--vendor-session",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Vendor session id for the aborting session"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_18[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token the action attaches to"},
    {.name          = "--kind",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Action kind (planner|coder|tool_call|heartbeat|...)"},
    {.name          = "--entity",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Optional entity ref kind:id"},
    {.name          = "--vendor-role",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Optional vendor role tag"},
    {.name          = "--repo-root",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Absolute path of checkout to probe locality against"},
    {.name          = "--no-locality-probe",
     .kind          = "bool",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Skip the git locality probe"},
    {.name          = "--metadata",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Opaque text (typically JSON) persisted on the action row; validated as well-formed JSON when supplied"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_19[] = {
    {.name          = "--action",
     .kind          = "int",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Action id returned by `action start`"},
    {.name          = "--outcome",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = "ok",
     .description   = "ok | error | aborted | timeout (default ok)"},
    {.name          = "--summary",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Optional free-text summary recorded on the action"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_20[] = {
    {.name          = "--plan",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Plan id the run belongs to"},
    {.name          = "--workflow",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Workflow name (e.g. isolated-sequential)"},
    {.name          = "--run-id",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Unique run identifier (run-<pid>-<nanos>)"},
    {.name          = "--pid",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "PID of the external workflow harness process"},
    {.name          = "--repo-root",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Absolute path of the repo root the harness is driving"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_21[] = {
    {.name          = "--run-id",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "The run identifier (run-<pid>-<nanos>) returned by run start"},
    {.name          = "--status",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Terminal status: completed | failed | interrupted"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_22[] = {
    {.name          = "--task",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Task id this dispatch targets"},
    {.name          = "--work-item",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Logical work item id"},
    {.name = "--project", .kind = "string", .required = true, .list = false, .default_value = {}, .description = "Project id"},
    {.name          = "--validation-policy",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Validation policy version"},
    {.name          = "--routing-policy",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Routing policy version"},
    {.name          = "--profile-rule",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Profile rule version"},
    {.name          = "--vendor",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Vendor (opaque)"},
    {.name = "--role", .kind = "string", .required = true, .list = false, .default_value = {}, .description = "Role (opaque)"},
    {.name          = "--tier",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "small|medium|large"},
    {.name          = "--work-type",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "schema|engine|architectural|cli|feature|mechanical"},
    {.name          = "--complexity",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "bounded|standard|high-risk"},
    {.name          = "--packet-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Digest of the authoritative packet"},
    {.name          = "--profile-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Digest of the compiled profile"},
    {.name          = "--policy-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Digest of the policy snapshot"},
    {.name          = "--capability-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Digest of the host capability snapshot"},
    {.name          = "--candidate",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Requested candidate row id"},
    {.name          = "--host",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Host id whose capability snapshot was consulted"},
    {.name          = "--class",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "fallback|default|override|declared_experiment"},
    {.name          = "--experiment",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Experiment id (required for declared_experiment)"},
    {.name          = "--claim",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Claim token this dispatch is bound to"},
    {.name          = "--claim-status",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Claim status observed at preview time"},
    {.name          = "--evidence-state",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "evidential|observational"},
    {.name          = "--expires-at",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "RFC3339 instant after which the token is dead"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_23[] = {
    {.name          = "--token",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Preview token to spend"},
    {.name          = "--dispatch-key",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Unique key for the resulting dispatch"},
    {.name          = "--now",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "RFC3339 instant to evaluate expiry against"},
    {.name          = "--packet-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently observed packet digest"},
    {.name          = "--profile-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently observed profile digest"},
    {.name          = "--policy-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently observed policy digest"},
    {.name          = "--capability-digest",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently observed capability digest"},
    {.name          = "--candidate",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently resolved candidate row id"},
    {.name          = "--vendor",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently resolved vendor"},
    {.name          = "--role",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently resolved role"},
    {.name          = "--tier",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently resolved tier"},
    {.name          = "--work-type",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently resolved work type"},
    {.name          = "--complexity",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently resolved complexity"},
    {.name          = "--validation-policy",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently active validation policy version"},
    {.name          = "--routing-policy",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Currently active routing policy version"},
    {.name          = "--claim",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Currently held claim token"},
    {.name          = "--claim-status",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Currently observed claim status"},
    {.name          = "--reviewer",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Reviewer disposition to record (default required)"},
    {.name          = "--decision",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "confirmed|overridden (default confirmed)"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_24[] = {
    {.name          = "--claim",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Claim token that owns this context record"},
    {.name          = "--kind",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Record kind: finding|risk|artifact|followup|summary|capsule"},
    {.name = "--body", .kind = "string", .required = true, .list = false, .default_value = {}, .description = "Record body text"},
    {.name          = "--compiled-from",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Comma-separated context_record ids this capsule was compiled from (capsule kind only)"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_25[] = {
    {.name          = "--run",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "workflow_runs.id — the run that owns this capsule"},
    {.name          = "--stage",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Stage name this capsule distills (e.g. 'plan', 'code')"},
    {.name          = "--body",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Compiled capsule body text"},
    {.name          = "--compiled-from",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Comma-separated context_record ids this capsule distills (provenance)"},
    {.name          = "--session",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "session_id (integer). Optional — an ephemeral session is created when omitted."},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_26[] = {
    {.name          = "--run",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Run id (integer) to query"},
    {.name          = "--stage",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Filter to records from this stage"},
    {.name          = "--status",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Filter by status: active|consumed|superseded"},
    {.name          = "--kind",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Filter by kind: finding|risk|artifact|followup|summary|capsule"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};
constexpr flag_spec k_flags_27[] = {
    {.name          = "--id",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Single record id to transition"},
    {.name          = "--run",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Run id for bulk stage sweep (use with --stage)"},
    {.name          = "--stage",
     .kind          = "string",
     .required      = false,
     .list          = false,
     .default_value = {},
     .description   = "Stage name for bulk sweep (use with --run)"},
    {.name          = "--status",
     .kind          = "string",
     .required      = true,
     .list          = false,
     .default_value = {},
     .description   = "Target status: consumed|superseded"},
    {.name = "--json", .kind = "bool", .required = false, .list = false, .default_value = {}, .description = ""},
};

constexpr positional_spec k_pos_1[] = {
    {.name = "plan-id", .required = true, .description = "Plan id to pull from"},
};
constexpr positional_spec k_pos_2[] = {
    {.name = "plan-id", .required = true, .description = "Plan id to peek into"},
};

} // namespace

/// @brief Every command node `planar-agent` declares, as a flat list.
///
/// This is the declarative surface the CLI11 tree is built from and the
/// schema catalog is emitted from — one description of the verb set, not
/// two that can drift. `catalog_parity.hpp` diffs it against the Zig
/// oracle's own `schema` output, so a node added here without a handler is
/// caught by dispatch's registration gate rather than shipping as a verb
/// that silently exits 0.
///
/// @return One `node_spec` per command node, in declaration order.
auto surface_nodes() -> std::vector<node_spec> {
  return {
      {.path        = k_path_0,
       .description = "Print the planar-agent version, commit, and zig runtime.",
       .flags       = {},
       .positionals = {},
       .group       = false},
      {.path        = k_path_1,
       .description = "Atomically pick the next eligible task, claim it, and flip status to doing.",
       .flags       = k_flags_1,
       .positionals = k_pos_1,
       .group       = false},
      {.path        = k_path_2,
       .description = "Read-only what's-next selector (same query as pull, no writes).",
       .flags       = k_flags_2,
       .positionals = k_pos_2,
       .group       = false},
      {.path        = k_path_3,
       .description = "Atomically end the work session: task → done, claim → completed.",
       .flags       = k_flags_3,
       .positionals = {},
       .group       = false},
      {.path        = k_path_4,
       .description = "Atomically fail the work session: task → todo, claim → aborted.",
       .flags       = k_flags_4,
       .positionals = {},
       .group       = false},
      {.path        = k_path_5,
       .description = "Graceful give-up: task → todo, claim → released (vs fail's aborted).",
       .flags       = k_flags_5,
       .positionals = {},
       .group       = false},
      {.path        = k_path_6,
       .description = "Atomically park the task on an external blocker.",
       .flags       = k_flags_6,
       .positionals = {},
       .group       = false},
      {.path        = k_path_7,
       .description = "Direct entity claim; task claims atomically transition todo to doing by default.",
       .flags       = k_flags_7,
       .positionals = {},
       .group       = false},
      {.path        = k_path_8,
       .description = "Refresh the lease on an active claim.",
       .flags       = k_flags_8,
       .positionals = {},
       .group       = false},
      {.path        = k_path_9,
       .description = "Associate a pre-acquired active claim with a workflow run (and optional stage). Used by an external "
                      "workflow harness at dispatch time.",
       .flags       = k_flags_9,
       .positionals = {},
       .group       = false},
      {.path        = k_path_10,
       .description = "Nested action lifecycle (sub-tool-calls inside a claim).",
       .flags       = {},
       .positionals = {},
       .group       = true},
      {.path        = k_path_11,
       .description = "Translate a vendor hook event into store primitives (claude + copilot adapters wired; codex reserved).",
       .flags       = k_flags_11,
       .positionals = {},
       .group       = false},
      {.path        = k_path_12,
       .description = "Operator recovery: mark expired claims stale, close orphaned actions, abandon dead runs.",
       .flags       = k_flags_12,
       .positionals = {},
       .group       = false},
      {.path        = k_path_13,
       .description = "Operator force-release of a stuck claim (any session, not just the owner).",
       .flags       = k_flags_13,
       .positionals = {},
       .group       = false},
      {.path        = k_path_14,
       .description = "Print the full command tree as a JSON catalog (flags, aliases, positionals).",
       .flags       = {},
       .positionals = {},
       .group       = false},
      {.path        = k_path_15,
       .description = "Workflow run lifecycle (start / end). Used by an external workflow harness to stay DB-handle-free.",
       .flags       = {},
       .positionals = {},
       .group       = true},
      {.path        = k_path_16,
       .description = "Routing dispatch authorization (preview / confirm). Binds current state to a single-use token.",
       .flags       = {},
       .positionals = {},
       .group       = true},
      {.path        = k_path_17,
       .description = "Run-scoped working-memory records (add / list / resolve / capsule). Used by an external workflow harness.",
       .flags       = {},
       .positionals = {},
       .group       = true},
      {.path        = k_path_18,
       .description = "Start a nested action under a claim (child of the claim's role action).",
       .flags       = k_flags_18,
       .positionals = {},
       .group       = false},
      {.path        = k_path_19,
       .description = "Close a nested action started under a claim.",
       .flags       = k_flags_19,
       .positionals = {},
       .group       = false},
      {.path        = k_path_20,
       .description = "Insert a workflow_runs row in running status.",
       .flags       = k_flags_20,
       .positionals = {},
       .group       = false},
      {.path        = k_path_21,
       .description = "Close a workflow_runs row with a terminal status (completed|failed|interrupted).",
       .flags       = k_flags_21,
       .positionals = {},
       .group       = false},
      {.path        = k_path_22,
       .description = "Bind current routing state to a single-use, expiry-bound confirmation token.",
       .flags       = k_flags_22,
       .positionals = {},
       .group       = false},
      {.path        = k_path_23,
       .description = "Revalidate a preview token against current state and atomically write the dispatch snapshot.",
       .flags       = k_flags_23,
       .positionals = {},
       .group       = false},
      {.path        = k_path_24,
       .description = "Write a context_records row stamped from the claim's run_id, stage, session_id.",
       .flags       = k_flags_24,
       .positionals = {},
       .group       = false},
      {.path        = k_path_25,
       .description = "Write a compiled capsule context_records row, run-keyed (claim_id=NULL, decision 456).",
       .flags       = k_flags_25,
       .positionals = {},
       .group       = false},
      {.path        = k_path_26,
       .description = "List context_records for a run, with optional stage/status/kind filters.",
       .flags       = k_flags_26,
       .positionals = {},
       .group       = false},
      {.path        = k_path_27,
       .description = "Transition context_records active → consumed|superseded (single record or bulk stage sweep).",
       .flags       = k_flags_27,
       .positionals = {},
       .group       = false},
  };
}

auto surface_summaries() -> std::span<std::pair<std::string_view, std::string_view> const> {
  static constexpr std::pair<std::string_view, std::string_view> k_summaries[] = {
      {"planar-agent", "Agent-callable coordination binary (pull / claim / complete / heartbeat / reconcile)."},
      {"planar-agent version", "Print the planar-agent version, commit, and zig runtime."},
      {"planar-agent pull", "Atomically pick the next eligible task, claim it, and flip status to doing."},
      {"planar-agent peek", "Read-only what's-next selector (same query as pull, no writes)."},
      {"planar-agent complete", "Atomically end the work session: task → done, claim → completed."},
      {"planar-agent fail", "Atomically fail the work session: task → todo, claim → aborted."},
      {"planar-agent release", "Graceful give-up: task → todo, claim → released (vs fail's aborted)."},
      {"planar-agent block", "Atomically park the task on an external blocker."},
      {"planar-agent claim", "Direct entity claim; task claims atomically transition todo to doing by default."},
      {"planar-agent heartbeat", "Refresh the lease on an active claim."},
      {"planar-agent claim-associate", "Associate a pre-acquired active claim with a workflow run (and optional stage). Used by "
                                       "an external workflow harness at dispatch time."},
      {"planar-agent action", "Nested action lifecycle (sub-tool-calls inside a claim)."},
      {"planar-agent action start", "Start a nested action under a claim (child of the claim's role action)."},
      {"planar-agent action end", "Close a nested action started under a claim."},
      {"planar-agent ingest",
       "Translate a vendor hook event into store primitives (claude + copilot adapters wired; codex reserved)."},
      {"planar-agent reconcile", "Operator recovery: mark expired claims stale, close orphaned actions, abandon dead runs."},
      {"planar-agent abort", "Operator force-release of a stuck claim (any session, not just the owner)."},
      {"planar-agent schema", "Print the full command tree as a JSON catalog (flags, aliases, positionals)."},
      {"planar-agent run", "Workflow run lifecycle (start / end). Used by an external workflow harness to stay DB-handle-free."},
      {"planar-agent run start", "Insert a workflow_runs row in running status."},
      {"planar-agent run end", "Close a workflow_runs row with a terminal status (completed|failed|interrupted)."},
      {"planar-agent dispatch", "Routing dispatch authorization (preview / confirm). Binds current state to a single-use token."},
      {"planar-agent dispatch preview", "Bind current routing state to a single-use, expiry-bound confirmation token."},
      {"planar-agent dispatch confirm",
       "Revalidate a preview token against current state and atomically write the dispatch snapshot."},
      {"planar-agent context",
       "Run-scoped working-memory records (add / list / resolve / capsule). Used by an external workflow harness."},
      {"planar-agent context add", "Write a context_records row stamped from the claim's run_id, stage, session_id."},
      {"planar-agent context capsule", "Write a compiled capsule context_records row, run-keyed (claim_id=NULL, decision 456)."},
      {"planar-agent context list", "List context_records for a run, with optional stage/status/kind filters."},
      {"planar-agent context resolve",
       "Transition context_records active → consumed|superseded (single record or bulk stage sweep)."},
  };
  return k_summaries;
}

auto unported_paths() -> std::span<std::string_view const> {
  static constexpr std::string_view k_unported[] = {
      "ingest",
  };
  return k_unported;
}

} // namespace planar::cmd::agent
