//! Build-time codegen: scan a migrations directory of paired
//! NNNNN_<name>.up.sql / NNNNN_<name>.down.sql files and emit a Zig
//! source file exposing them as a compile-time `[]const Migration`
//! array. Run by build.zig; never invoked by hand.
//!
//! Usage: gen_migrations <migrations-dir> <output-file>
const std = @import("std");
const Io = std.Io;

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) {
        std.debug.print("usage: {s} <migrations-dir> <output-file>\n", .{args[0]});
        std.process.exit(2);
    }
    const dir_path = args[1];
    const out_path = args[2];

    var cwd = Io.Dir.cwd();
    var dir = try cwd.openDir(io, dir_path, .{ .iterate = true });
    defer dir.close(io);

    // Collect *.up.sql filenames, sort lexically.
    var names: std.ArrayList([]const u8) = .empty;
    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".up.sql")) continue;
        try names.append(arena, try arena.dupe(u8, entry.name));
    }
    std.mem.sort([]const u8, names.items, {}, struct {
        fn lt(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.order(u8, a, b) == .lt;
        }
    }.lt);

    var out_file = try cwd.createFile(io, out_path, .{ .truncate = true });
    defer out_file.close(io);
    var write_buf: [4096]u8 = undefined;
    var fw = out_file.writer(io, &write_buf);
    const w = &fw.interface;

    try w.writeAll(
        \\// AUTO-GENERATED by tools/gen_migrations.zig. Do not edit.
        \\
        \\pub const Migration = struct {
        \\    version: u32,
        \\    name: []const u8,
        \\    up: [:0]const u8,
        \\    down: [:0]const u8,
        \\};
        \\
        \\pub const all = [_]Migration{
        \\
    );

    for (names.items) |up_name| {
        // up_name: "NNNNN_<name>.up.sql"
        const stem = up_name[0 .. up_name.len - ".up.sql".len];
        const underscore = std.mem.indexOfScalar(u8, stem, '_') orelse {
            std.debug.print("skip {s}: no underscore\n", .{up_name});
            continue;
        };
        const num_str = stem[0..underscore];
        const name = stem[underscore + 1 ..];
        const version = try std.fmt.parseInt(u32, num_str, 10);

        const limit: Io.Limit = .limited(16 * 1024 * 1024);
        const up_buf = try dir.readFileAlloc(io, up_name, arena, limit);
        const down_name = try std.fmt.allocPrint(arena, "{s}.down.sql", .{stem});
        const down_buf = try dir.readFileAlloc(io, down_name, arena, limit);

        try w.print("    .{{\n        .version = {d},\n        .name = \"{s}\",\n        .up =\n", .{ version, name });
        try emitMultilineLiteral(w, up_buf);
        try w.writeAll("\n        ,\n        .down =\n");
        try emitMultilineLiteral(w, down_buf);
        try w.writeAll("\n        ,\n    },\n");
    }

    try w.writeAll("};\n");
    try w.flush();
}

/// Emit `content` as a Zig multi-line string literal. Each `\n` in `content`
/// becomes a line break between consecutive `\\`-prefixed lines.
///
/// Zig concatenates consecutive `\\` lines with `\n` between (none after the
/// last), so a trailing `\n` in `content` produces an extra empty `\\` line
/// — exactly what splitScalar yields after a trailing delimiter.
fn emitMultilineLiteral(w: anytype, content: []const u8) !void {
    var it = std.mem.splitScalar(u8, content, '\n');
    var first = true;
    while (it.next()) |line| {
        if (!first) try w.writeAll("\n");
        first = false;
        try w.writeAll("            \\\\");
        try w.writeAll(line);
    }
}
