//! Build-time codegen: walk a templates `defaults/` directory and emit a Zig
//! source file exposing every `<system>/<kind>.json` file as a compile-time
//! `[]const TemplateFile` array. Run by build.zig; never invoked by hand.
//!
//! The Go side embeds its baseline templates via `embed.FS` rooted at
//! `internal/templates/defaults/`. Zig has no `embed.FS` equivalent at
//! comptime that can also walk a tree, so we generate a flat array at
//! build time and let the loader iterate it.
//!
//! Usage: gen_templates <defaults-dir> <output-file>
const std = @import("std");
const Io = std.Io;

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) {
        std.debug.print("usage: {s} <defaults-dir> <output-file>\n", .{args[0]});
        std.process.exit(2);
    }
    const dir_path = args[1];
    const out_path = args[2];

    var cwd = Io.Dir.cwd();
    var root = try cwd.openDir(io, dir_path, .{ .iterate = true });
    defer root.close(io);

    // Collect (system, kind, body) triples by walking <dir>/<system>/<kind>.json.
    const Entry = struct {
        system: []const u8,
        kind: []const u8,
        body: []const u8,
    };
    var entries: std.ArrayList(Entry) = .empty;

    var root_it = root.iterate();
    while (try root_it.next(io)) |sys_entry| {
        if (sys_entry.kind != .directory) continue;
        const system_name = try arena.dupe(u8, sys_entry.name);

        var sys_dir = try root.openDir(io, system_name, .{ .iterate = true });
        defer sys_dir.close(io);

        var sys_it = sys_dir.iterate();
        while (try sys_it.next(io)) |file_entry| {
            if (file_entry.kind != .file) continue;
            if (!std.mem.endsWith(u8, file_entry.name, ".json")) continue;
            const fname = try arena.dupe(u8, file_entry.name);
            const kind = fname[0 .. fname.len - ".json".len];
            const limit: Io.Limit = .limited(4 * 1024 * 1024);
            const body = try sys_dir.readFileAlloc(io, fname, arena, limit);
            try entries.append(arena, .{
                .system = system_name,
                .kind = kind,
                .body = body,
            });
        }
    }

    // Sort by (system, kind) so output is deterministic.
    std.mem.sort(Entry, entries.items, {}, struct {
        fn lt(_: void, a: Entry, b: Entry) bool {
            const ord = std.mem.order(u8, a.system, b.system);
            if (ord != .eq) return ord == .lt;
            return std.mem.order(u8, a.kind, b.kind) == .lt;
        }
    }.lt);

    var out_file = try cwd.createFile(io, out_path, .{ .truncate = true });
    defer out_file.close(io);
    var write_buf: [4096]u8 = undefined;
    var fw = out_file.writer(io, &write_buf);
    const w = &fw.interface;

    try w.writeAll(
        \\// AUTO-GENERATED by src-zig/tools/gen_templates.zig. Do not edit.
        \\
        \\pub const TemplateFile = struct {
        \\    system: []const u8,
        \\    kind: []const u8,
        \\    body: []const u8,
        \\};
        \\
        \\pub const all = [_]TemplateFile{
        \\
    );

    for (entries.items) |e| {
        try w.print("    .{{\n        .system = \"{s}\",\n        .kind = \"{s}\",\n        .body =\n", .{ e.system, e.kind });
        try emitMultilineLiteral(w, e.body);
        try w.writeAll("\n        ,\n    },\n");
    }

    try w.writeAll("};\n");
    try w.flush();
}

/// Emit `content` as a Zig multi-line string literal. Each `\n` in `content`
/// becomes a line break between consecutive `\\`-prefixed lines.
fn emitMultilineLiteral(w: anytype, content: []const u8) !void {
    var it = std.mem.splitScalar(u8, content, '\n');
    var first = true;
    while (it.next()) |line| {
        if (!first) try w.writeAll("\n");
        first = false;
        try w.writeAll("            \\\\");
        try w.writeAll(line);
    }
}
