# planar_generate_migrations() — configure-time codegen for D5's
# `#embed`-backed migration modules (tech-spec § "Embedded migrations and
# templates"; plan 996 task cpp-db-migrations-embed).
#
# Enumerates `<MIGRATIONS_DIR>/*.up.sql`, sorts the filenames EXPLICITLY
# (never relies on file(GLOB)'s underlying directory order — the tech-spec
# mandate), and writes a generated C++ implementation unit for MODULE_NAME
# that `#embed`s each up/down SQL pair, into OUT_FILE — always a path under
# the build tree, never the source tree.
#
# One call per migration stream (plan 1080, task hq-agentdb-migrations).
# The stream's identity in the generated unit is fully parameterized so a
# second stream lands in its own module without sharing a symbol with the
# first:
#
#   MODULE_NAME     the module the unit implements (`planar.db.migrations`,
#                   `planar.db.migrations_agent`)
#   NAMESPACE       the C++ namespace the accessor is defined in
#                   (default `planar::db`)
#   ACCESSOR        the accessor function name (default `migrations`)
#   INTERFACE_UNIT  the hand-authored interface unit named in the header
#                   comment (default `src/lib/db/migrations.cppm`)
#
# The defaults reproduce the main stream's unit byte for byte, so the main
# database's embedded chain does not change when a second stream is added.
# The version table a stream writes to is not the codegen's business — the
# migration SQL writes it and `src/lib/db/migrate.cppm` takes it as a
# parameter — so it is not an argument here.
#
# `file(GLOB ... CONFIGURE_DEPENDS)` makes CMake re-run configure (and thus
# regenerate OUT_FILE) whenever a migration file is added or removed —
# no separate build-time custom command is needed for that case.

function(planar_generate_migrations)
  set(one_value_args MIGRATIONS_DIR OUT_FILE MODULE_NAME NAMESPACE ACCESSOR INTERFACE_UNIT)
  cmake_parse_arguments(ARG "" "${one_value_args}" "" ${ARGN})

  if(NOT ARG_MIGRATIONS_DIR OR NOT ARG_OUT_FILE OR NOT ARG_MODULE_NAME)
    message(FATAL_ERROR
      "planar_generate_migrations: MIGRATIONS_DIR, OUT_FILE, and MODULE_NAME are all required")
  endif()
  if(NOT ARG_NAMESPACE)
    set(ARG_NAMESPACE "planar::db")
  endif()
  if(NOT ARG_ACCESSOR)
    set(ARG_ACCESSOR "migrations")
  endif()
  if(NOT ARG_INTERFACE_UNIT)
    set(ARG_INTERFACE_UNIT "src/lib/db/migrations.cppm")
  endif()
  get_filename_component(_dir_name "${ARG_MIGRATIONS_DIR}" NAME)

  file(GLOB _up_paths CONFIGURE_DEPENDS "${ARG_MIGRATIONS_DIR}/*.up.sql")
  if(NOT _up_paths)
    message(FATAL_ERROR
      "planar_generate_migrations: no *.up.sql files found under ${ARG_MIGRATIONS_DIR}")
  endif()

  set(_names "")
  foreach(_p IN LISTS _up_paths)
    get_filename_component(_n "${_p}" NAME)
    list(APPEND _names "${_n}")
  endforeach()

  # Explicit lexicographic sort by filename (NOT by whatever order
  # file(GLOB) happened to return). The zero-padded NNNNN prefix makes
  # lexicographic order equal numeric order — see migrations/README.md.
  list(SORT _names)

  set(_content
"// AUTO-GENERATED by cmake/generate_migrations.cmake. Do not edit.
// Regenerated every configure from ${_dir_name}/*.up.sql / *.down.sql,
// sorted explicitly by the NNNNN filename prefix (never file(GLOB) order).
// See ${ARG_INTERFACE_UNIT} for the hand-authored interface this
// implementation unit satisfies.

module;

module ${ARG_MODULE_NAME};

import std;

namespace ${ARG_NAMESPACE} {
namespace {

")

  set(_entries "")
  set(_index 0)
  foreach(_up_name IN LISTS _names)
    string(REGEX MATCH "^([0-9]+)_(.+)\\.up\\.sql$" _m "${_up_name}")
    if(NOT _m)
      message(FATAL_ERROR
        "planar_generate_migrations: unrecognized migration filename "
        "'${_up_name}' (expected NNNNN_<name>.up.sql)")
    endif()
    set(_ver_str "${CMAKE_MATCH_1}")
    set(_stem_name "${CMAKE_MATCH_2}")

    # Strip leading zeros before emitting as a C++ decimal literal —
    # `00008` would otherwise be parsed as an (invalid) octal literal by
    # both CMake's math(EXPR) and C++ itself.
    string(REGEX REPLACE "^0+" "" _ver_decimal "${_ver_str}")
    if(_ver_decimal STREQUAL "")
      set(_ver_decimal "0")
    endif()

    set(_down_name "${_ver_str}_${_stem_name}.down.sql")
    set(_up_path "${ARG_MIGRATIONS_DIR}/${_up_name}")
    set(_down_path "${ARG_MIGRATIONS_DIR}/${_down_name}")
    if(NOT EXISTS "${_down_path}")
      message(FATAL_ERROR
        "planar_generate_migrations: missing down migration '${_down_path}' "
        "for '${_up_name}'")
    endif()

    string(APPEND _content
      "constexpr unsigned char k_up_${_index}[] = {\n#embed \"${_up_path}\"\n};\n"
      "constexpr unsigned char k_down_${_index}[] = {\n#embed \"${_down_path}\"\n};\n\n")

    string(APPEND _entries
      "  migration_record{\n"
      "    .version_  = ${_ver_decimal},\n"
      "    .name_     = \"${_stem_name}\",\n"
      "    .up_sql_   = std::string_view(reinterpret_cast<const char*>(k_up_${_index}), sizeof(k_up_${_index})),\n"
      "    .down_sql_ = std::string_view(reinterpret_cast<const char*>(k_down_${_index}), sizeof(k_down_${_index})),\n"
      "  },\n")

    math(EXPR _index "${_index} + 1")
  endforeach()

  # `const`, not `constexpr`: each entry's up_sql_/down_sql_ is built via
  # reinterpret_cast<const char*> over a #embed'd byte array, which is not
  # a core constant expression — the array is still statically allocated
  # and dynamically initialized exactly once, before main().
  string(APPEND _content
    "const migration_record k_all[] = {\n${_entries}};\n\n"
    "} // namespace\n\n"
    "auto ${ARG_ACCESSOR}() -> std::span<migration_record const> {\n"
    "  return k_all;\n"
    "}\n\n"
    "} // namespace ${ARG_NAMESPACE}\n")

  # WRITE-IF-DIFFERENT (plan 996, task 6061). An unconditional file(WRITE)
  # rewrites this translation unit on EVERY configure, which bumps its
  # mtime and forces a rebuild of planar_db and everything downstream even
  # when not one byte changed — the exact rebuild churn CLAUDE.md's two
  # build-cache invariants exist against.
  #
  # The unconditional rewrite also happened to cover the case
  # CONFIGURE_DEPENDS does not: that glob re-triggers only when the SET of
  # matched files changes, not when a matched file's CONTENT changes.
  # Dropping the rewrite is safe anyway, and MEASURED rather than assumed:
  # clang emits every `#embed` input into the depfile, so ninja rebuilds
  # this TU on a .sql content edit through its own dependency graph.
  # Verified with `ninja -C build/debug -t deps` — the entry for
  # migrations.generated.cpp.o lists all 66 up/down .sql files. (Editing a
  # released migration in place is forbidden regardless; see
  # migrations/README.md.)
  set(_existing "")
  if(EXISTS "${ARG_OUT_FILE}")
    file(READ "${ARG_OUT_FILE}" _existing)
  endif()
  if(NOT _existing STREQUAL _content)
    file(WRITE "${ARG_OUT_FILE}" "${_content}")
  endif()
endfunction()
