# planar_generate_templates() — configure-time codegen for D5's
# `#embed`-backed `planar.engine.config.templates_embed` module (tech-spec
# § "Embedded migrations and templates"; plan 996 task 6032, mirroring
# generate_migrations.cmake's discipline exactly).
#
# Enumerates `<TEMPLATES_DIR>/<system>/<kind>.json`, sorts EXPLICITLY by the
# `(system, kind)` tuple (never relies on file(GLOB)'s underlying directory
# order — the tech-spec mandate, same as migrations), and writes a
# generated C++ implementation unit for `planar.engine.config.templates_embed`
# that `#embed`s each file, into OUT_FILE — always a path under the build
# tree, never the source tree.
#
# `file(GLOB ... CONFIGURE_DEPENDS)` makes CMake re-run configure (and thus
# regenerate OUT_FILE) whenever a template file is added or removed — no
# separate build-time custom command is needed for that case.
#
# Tuple-vs-path-string sort pitfall: sorting the raw "<system>/<kind>.json"
# relative path as one string is NOT always equivalent to sorting the
# (system, kind) tuple — if one system directory name were a proper prefix
# of another (e.g. "github" vs "github-issues"), '-' (0x2D) sorts BEFORE
# '/' (0x2F) in ASCII, so the joined-path string order could diverge from
# tuple order at that boundary. Building the sort key as
# "<system>\t<kind>" (tab, 0x09) sidesteps this: 0x09 sorts before every
# character legal in a system/kind name (lowercase alnum + '-'), so
# tab-joined sort order reproduces `(system, kind)` tuple order exactly,
# regardless of prefix relationships between directory names — matching
# `zig/tools/gen_templates.zig`'s explicit `(system, kind)` comparator.

function(planar_generate_templates)
  set(one_value_args TEMPLATES_DIR OUT_FILE MODULE_NAME)
  cmake_parse_arguments(ARG "" "${one_value_args}" "" ${ARGN})

  if(NOT ARG_TEMPLATES_DIR OR NOT ARG_OUT_FILE OR NOT ARG_MODULE_NAME)
    message(FATAL_ERROR
      "planar_generate_templates: TEMPLATES_DIR, OUT_FILE, and MODULE_NAME are all required")
  endif()

  # CONFIGURE_DEPENDS on the OUTER glob too (plan 996, task 6084). The
  # inner *.json glob has always carried it, so adding a template to an
  # EXISTING system directory re-triggers configure — but adding a whole
  # new templates/defaults/<system>/ did not, and the new system was
  # silently absent from the embedded set until someone reconfigured by
  # hand. A silently-missing propagation system is a much worse failure
  # than a slightly slower build check.
  file(GLOB _system_dirs LIST_DIRECTORIES true CONFIGURE_DEPENDS "${ARG_TEMPLATES_DIR}/*")
  if(NOT _system_dirs)
    message(FATAL_ERROR
      "planar_generate_templates: no system directories found under ${ARG_TEMPLATES_DIR}")
  endif()

  set(_sort_keys "")
  foreach(_sys_dir IN LISTS _system_dirs)
    if(NOT IS_DIRECTORY "${_sys_dir}")
      continue()
    endif()
    get_filename_component(_system "${_sys_dir}" NAME)

    file(GLOB _kind_paths CONFIGURE_DEPENDS "${_sys_dir}/*.json")
    foreach(_kp IN LISTS _kind_paths)
      # Strip ONLY the `.json` suffix (plan 996, task 6084). NAME_WE splits
      # at the FIRST dot, so `zig/tools/gen_templates.zig`'s kind for
      # `issue.v2.json` is `issue.v2` where NAME_WE answered `issue` — a
      # silently different kind name in the embedded set, and one that
      # would then never match a lookup. LAST_EXT semantics, expressed
      # directly so the intent survives a reader who does not know the
      # NAME_WE / NAME_WLE distinction.
      get_filename_component(_kind "${_kp}" NAME)
      string(REGEX REPLACE "\\.json$" "" _kind "${_kind}")
      list(APPEND _sort_keys "${_system}\t${_kind}")
    endforeach()
  endforeach()

  if(NOT _sort_keys)
    message(FATAL_ERROR
      "planar_generate_templates: no *.json template files found under ${ARG_TEMPLATES_DIR}/*/")
  endif()

  list(SORT _sort_keys)

  set(_content
"// AUTO-GENERATED by cmake/generate_templates.cmake. Do not edit.
// Regenerated every configure from templates/defaults/<system>/<kind>.json,
// sorted explicitly by (system, kind) (never file(GLOB) order). See
// src/engine/config/templates_embed.cppm for the hand-authored
// interface this implementation unit satisfies.

module;

module ${ARG_MODULE_NAME};

import std;

namespace planar::engine::config {
namespace {

")

  set(_entries "")
  set(_index 0)
  foreach(_key IN LISTS _sort_keys)
    string(REPLACE "\t" ";" _parts "${_key}")
    list(GET _parts 0 _system)
    list(GET _parts 1 _kind)
    set(_body_path "${ARG_TEMPLATES_DIR}/${_system}/${_kind}.json")
    if(NOT EXISTS "${_body_path}")
      message(FATAL_ERROR
        "planar_generate_templates: expected template file '${_body_path}' not found")
    endif()

    string(APPEND _content
      "constexpr unsigned char k_body_${_index}[] = {\n#embed \"${_body_path}\"\n};\n\n")

    string(APPEND _entries
      "  template_file{\n"
      "    .system = \"${_system}\",\n"
      "    .kind   = \"${_kind}\",\n"
      "    .body   = std::string_view(reinterpret_cast<const char*>(k_body_${_index}), sizeof(k_body_${_index})),\n"
      "  },\n")

    math(EXPR _index "${_index} + 1")
  endforeach()

  # `const`, not `constexpr`: each entry's `body` is built via
  # reinterpret_cast<const char*> over a #embed'd byte array, which is not
  # a core constant expression — the array is still statically allocated
  # and dynamically initialized exactly once, before main() (same rationale
  # as generate_migrations.cmake's k_all).
  string(APPEND _content
    "const template_file k_all[] = {\n${_entries}};\n\n"
    "} // namespace\n\n"
    "auto embedded_templates() -> std::span<template_file const> {\n"
    "  return k_all;\n"
    "}\n\n"
    "} // namespace planar::engine::config\n")

  # Write-if-different, for the reason (and with the measured depfile
  # justification) spelled out in cmake/generate_migrations.cmake — this
  # generator had the identical unconditional-rewrite churn, and fixing
  # one while leaving the other would have left half the invariant
  # standing.
  set(_existing "")
  if(EXISTS "${ARG_OUT_FILE}")
    file(READ "${ARG_OUT_FILE}" _existing)
  endif()
  if(NOT _existing STREQUAL _content)
    file(WRITE "${ARG_OUT_FILE}" "${_content}")
  endif()
endfunction()
